'use strict';
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];
const KEY='l5s1-studio-v4',IDS=E.map(x=>x.id),REGIONS=['Sem sintomas','Apenas lombar','Nádega','Coxa','Panturrilha','Pé / dedos'];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let storageProblem='',storedRaw='',state=load(),currentDetail='prone',activeFilter='Todos',currentScreen='home',detailOrigin='exercises',mapView='back',timerStart=null,toastHandle,undoAction=null;
let archiveDay=MotionStore.localDay(),calendarDate=new Date(archiveDay+'T12:00:00'),routineDraft=[],editingRecord=null,noteDay=archiveDay,pendingSession=null;
function load(){try{storedRaw=localStorage.getItem(KEY)||'{}';return MotionStore.normalize(JSON.parse(storedRaw),IDS);}catch(e){storageProblem=e.message;return MotionStore.defaults();}}
function save(){if(storageProblem){toast('Não foi possível ler seus dados. Importe um backup para continuar.');return false;}try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch(e){toast('Não foi possível salvar. Exporte um backup antes de sair.');return false;}}
function commit(change){const previous=JSON.parse(JSON.stringify(state));try{change();if(save())return true;state=previous;return false;}catch(e){state=previous;throw e;}}
function ex(id){return E.find(x=>x.id===id)||E[0];}
function poster(x){return x.reference.kind==='video'?`./posters/${x.reference.poster}`:`./media/${x.reference.file}`;}
function media(x){return `./media/${x.reference.file}`;}
function uid(){return 'r-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10);}
function toast(t,undo=null){$('#toastText').textContent=t;undoAction=undo;$('#toastUndo').classList.toggle('hidden',!undo);$('#toast').classList.add('visible');clearTimeout(toastHandle);toastHandle=setTimeout(()=>{$('#toast').classList.remove('visible');undoAction=null;},undo?7000:4000);}
$('#toastUndo').onclick=()=>{const action=undoAction;undoAction=null;if(action)action();$('#toast').classList.remove('visible');};
function speak(t){if(!state.settings.voice)return;if(window.MotionNative){window.MotionNative.speak(t);return;}if(!('speechSynthesis'in window))return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='pt-BR';u.rate=.95;speechSynthesis.speak(u);}
function stopVoice(){if(window.MotionNative)window.MotionNative.stopSpeech();else if('speechSynthesis'in window)speechSynthesis.cancel();}
function applyTheme(){document.body.classList.toggle('light',!state.settings.dark);$('meta[name=theme-color]').content=state.settings.dark?'#101c2b':'#f3f6fa';if(window.MotionNative?.setDarkTheme)window.MotionNative.setDarkTheme(state.settings.dark);}
function dayRecords(day){return state.records.filter(r=>r.localDate===day).sort((a,b)=>a.date.localeCompare(b.date));}
function ensureToday(){const day=MotionStore.localDay();if(!Object.prototype.hasOwnProperty.call(state.dailyPlans,day)&&!storageProblem)commit(()=>state.dailyPlans[day]=[...state.routine]);return day;}
function todayPlan(){return state.dailyPlans[MotionStore.localDay()]||state.routine;}
function longDate(day,weekday=false){return new Intl.DateTimeFormat('pt-BR',weekday?{weekday:'long',day:'numeric',month:'long'}:{day:'numeric',month:'long',year:'numeric'}).format(new Date(day+'T12:00:00'));}
function timeLabel(date){return new Date(date).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});}
function calcStreak(){const dates=new Set(state.records.map(r=>r.localDate).concat(state.sessions.filter(s=>s.exercises.length).map(s=>s.localDate)));let n=0,d=new Date();if(!dates.has(MotionStore.localDay(d)))d.setDate(d.getDate()-1);while(dates.has(MotionStore.localDay(d))){n++;d.setDate(d.getDate()-1);}return n;}
function pauseMedia(){for(const v of $$('video'))v.pause();pauseTimer();stopVoice();}
function showScreen(name,push=true){if(!['home','exercises','session','map','history','progress','detail'].includes(name))name='home';pauseMedia();currentScreen=name;$('#app').dataset.screen=name;$$('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===name));$$('.bottom-nav button').forEach(b=>{const active=b.dataset.nav===name||(name==='detail'&&b.dataset.nav==='exercises')||(['session','map'].includes(name)&&b.dataset.nav==='home');b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});
 if(push&&history.state?.screen!==name)history.pushState({screen:name},'',`#${name}`);
 if(name==='home')renderHome();if(name==='exercises')renderExercises();if(name==='session')renderSession();if(name==='map')renderMap();if(name==='history')renderArchive();if(name==='progress')renderProgress();window.scrollTo(0,0);
}
const TASKS=[['sun','Manhã','morning'],['chair','Pausas na cadeira','day'],['core','Core e fortalecimento','core'],['walk','Caminhada','walk']];
function renderHome(){const day=ensureToday(),plan=todayPlan(),records=dayRecords(day),done=new Set(records.map(r=>r.exerciseId)),completed=plan.filter(id=>done.has(id)).length,pct=plan.length?Math.round(completed/plan.length*100):0;
 $('#todayDate').textContent=longDate(day,true);$('#todayCount').parentElement.innerHTML=`<b id="todayCount">${done.size}</b> ${done.size===1?'exercício feito':'exercícios feitos'}`;const streak=calcStreak();$('#streakHome').parentElement.innerHTML=`<b id="streakHome">${streak}</b> ${streak===1?'dia seguido':'dias seguidos'}`;$('#todayPct').textContent=plan.length?`${pct}%`:'—';$('#todayProgress').value=pct;$('#todayProgressTitle').textContent=plan.length?(completed===plan.length?'Rotina de hoje concluída':`${completed} de ${plan.length} da sua rotina`):done.size?`${done.size} exercício${done.size===1?'':'s'} registrado${done.size===1?'':'s'}`:'Vamos montar sua rotina?';
 $('#homeStartSession').textContent=state.sessionDraft?'Continuar sessão pausada':plan.length?(completed===plan.length?'Fazer minha rotina novamente':'Iniciar minha rotina'):'Escolher meus exercícios';
 const items=[...plan,...[...done].filter(id=>!plan.includes(id))];
 $('#todayExercises').innerHTML=items.length?items.map((id,i)=>{const x=ex(id),r=records.filter(r=>r.exerciseId===id),on=r.length>0;return `<div class="daily-row ${on?'daily-done':''}"><button class="daily-open" data-daily-open="${id}"><span class="daily-number">${on?'✓':i+1}</span><span class="daily-copy"><b>${esc(x.name)}</b><small>${on?`Feito às ${timeLabel(r.at(-1).date)}${r.length>1?' • '+r.length+' registros':''}`:x.reference.kind==='video'?'Vídeo real • toque para consultar':'Imagem • toque para consultar'}${!plan.includes(id)?' • fora da rotina':''}</small></span></button><button class="log-check ${on?'done':''}" data-quick="${id}" aria-label="${on?'Editar registro de':'Marcar como feito:'} ${esc(x.name)}">${on?'✓':'+'}</button></div>`;}).join(''):'<div class="empty-state"><span class="empty-symbol">＋</span><h3>Uma rotina que é sua</h3><p>Selecione os exercícios que você pretende realizar. Depois, basta tocar em + para marcar cada um como feito.</p><button id="emptyRoutine" class="secondary">Escolher exercícios</button></div>';
 $$('[data-daily-open]').forEach(b=>b.onclick=()=>openDetail(b.dataset.dailyOpen,'home'));$$('[data-quick]').forEach(b=>b.onclick=()=>{const found=dayRecords(day).filter(r=>r.exerciseId===b.dataset.quick).at(-1);found?openRecord(found.exerciseId,day,found.id):quickLog(b.dataset.quick);});if($('#emptyRoutine'))$('#emptyRoutine').onclick=openRoutine;
 const note=state.dailyNotes[day];$('#todayNoteSummary').innerHTML=note&&(note.text||note.pain!==null||note.region!==null)?`${note.pain!==null?`<b>Dor ${note.pain}/10</b> · `:''}${note.region!==null?esc(regionLabel(note.region))+'<br>':''}${note.text?esc(note.text):'Toque para editar seu resumo.'}`:'Toque para registrar uma nota ou seus sintomas. Opcional.';
 $('#todayTasks').innerHTML=TASKS.map(([ic,t,k])=>`<button class="task-card" data-task="${k}"><span class="task-icon">${icon(ic)}</span><div><div class="task-title">${t}</div><div class="task-duration">${PRESETS[k].length} exercícios${k==='morning'?' • '+state.settings.morningTime:k==='core'?' • '+state.settings.coreTime:''}</div></div><span class="task-check">${state.doneTasks[day]?.includes(k)?'✓':'›'}</span></button>`).join('');$$('[data-task]').forEach(b=>b.onclick=()=>startSession(PRESETS[b.dataset.task],b.dataset.task));
}
function quickLog(id){const r={id:uid(),exerciseId:id,date:new Date().toISOString(),localDate:MotionStore.localDay(),source:'quick',sessionId:null,reps:null,seconds:null,sets:null,note:''};if(!commit(()=>state.records.push(r)))return;renderHome();toast('Exercício registrado para hoje.',()=>{if(commit(()=>state.records=state.records.filter(x=>x.id!==r.id))){refreshScreen();toast('Registro desfeito.');}});}
function refreshScreen(){if(currentScreen==='home')renderHome();if(currentScreen==='history')renderArchive();if(currentScreen==='progress')renderProgress();if(currentScreen==='exercises')renderExercises();}
function renderFilters(){const cats=['Todos','Centralização','Neural','Core','Cadeira','Atividade','Favoritos'];$('#exerciseFilters').innerHTML=cats.map(c=>`<button data-cat="${c}" class="${activeFilter===c?'active':''}" aria-pressed="${activeFilter===c}">${c}</button>`).join('');$$('[data-cat]').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.cat;renderFilters();renderExercises();});}
function renderExercises(){const q=$('#exerciseSearch').value.trim().toLocaleLowerCase('pt-BR'),plan=todayPlan();const list=E.filter(x=>(activeFilter==='Todos'||activeFilter===x.cat||(activeFilter==='Favoritos'&&state.favorites.includes(x.id)))&&(!q||(x.name+' '+x.sub).toLocaleLowerCase('pt-BR').includes(q)));
 $('#exerciseList').innerHTML=list.length?list.map(x=>`<div class="exercise-row"><button class="exercise-open" data-ex="${x.id}"><img class="exercise-thumb" src="${poster(x)}" alt="" loading="lazy"><div><h3>${esc(x.name)} ${state.favorites.includes(x.id)?'<span class="favorite-on">♥</span>':''}</h3><p>${esc(x.sub)}</p><span class="media-badge">${x.reference.kind==='video'?'VÍDEO REAL':'IMAGEM'}${x.review?' • REVISAR POSIÇÃO':''}</span></div></button><button data-plan-toggle="${x.id}" class="plan-toggle ${plan.includes(x.id)?'added':''}" aria-label="${plan.includes(x.id)?'Remover da':'Adicionar à'} rotina: ${esc(x.name)}" aria-pressed="${plan.includes(x.id)}">${plan.includes(x.id)?'✓':'+'}</button></div>`).join(''):'<div class="empty-state"><p>Nenhum exercício encontrado.</p></div>';$$('[data-ex]').forEach(b=>b.onclick=()=>openDetail(b.dataset.ex));$$('[data-plan-toggle]').forEach(b=>b.onclick=()=>togglePlan(b.dataset.planToggle));
}
function togglePlan(id){const day=ensureToday(),plan=[...todayPlan()],on=plan.includes(id),next=on?plan.filter(x=>x!==id):[...plan,id];if(commit(()=>{state.routine=next;state.dailyPlans[day]=[...next];})){renderExercises();if(currentScreen==='detail')updateDetailPlan();toast(on?'Removido da rotina. Registros feitos foram preservados.':'Adicionado à sua rotina diária.');}}
function openRoutine(){routineDraft=[...todayPlan()];$('#routineSearch').value='';renderRoutine();$('#routineDialog').showModal();}
function renderRoutine(){const q=$('#routineSearch').value.trim().toLocaleLowerCase('pt-BR');$('#routineOrder').innerHTML=routineDraft.length?routineDraft.map((id,i)=>`<div><span>${i+1}. ${esc(ex(id).name)}</span><button data-order-up="${i}" ${i===0?'disabled':''} aria-label="Mover para cima: ${esc(ex(id).name)}">↑</button><button data-order-down="${i}" ${i===routineDraft.length-1?'disabled':''} aria-label="Mover para baixo: ${esc(ex(id).name)}">↓</button></div>`).join(''):'<p class="subtle">Nenhum exercício selecionado.</p>';
 $('#routineChoices').innerHTML=E.filter(x=>(x.name+' '+x.sub).toLocaleLowerCase('pt-BR').includes(q)).map(x=>`<label><input type="checkbox" data-routine="${x.id}" ${routineDraft.includes(x.id)?'checked':''}>${esc(x.name)}</label>`).join('');$$('[data-routine]').forEach(b=>b.onchange=()=>{routineDraft=b.checked?[...routineDraft,b.dataset.routine]:routineDraft.filter(id=>id!==b.dataset.routine);renderRoutine();});for(const direction of ['up','down'])$$(`[data-order-${direction}]`).forEach(b=>b.onclick=()=>{const i=Number(b.dataset[direction==='up'?'orderUp':'orderDown']),j=i+(direction==='up'?-1:1);[routineDraft[i],routineDraft[j]]=[routineDraft[j],routineDraft[i]];renderRoutine();});}
function setMedia(kind,x){const v=$('#'+kind+'Video'),image=$('#'+kind+'Image'),button=$('#'+kind+'ImageButton'),isVideo=x.reference.kind==='video';v.pause();v.classList.toggle('hidden',!isVideo);button.classList.toggle('hidden',isVideo);$('#'+kind+'SpeedLabel').classList.toggle('hidden',!isVideo);
 if(isVideo){v.poster=poster(x);v.src=media(x);v.playbackRate=Number($('#'+kind+'Speed').value);v.load();}else{v.removeAttribute('src');v.load();image.src=media(x);image.alt=`Referência enviada: ${x.name}`;button.onclick=()=>openImage(x);}
 $('#'+kind+'DemoLabel').textContent=isVideo?'Movimento real • vídeo enviado por você':'Imagem estática • toque para ampliar';$('#'+kind+'Review').textContent=x.review;$('#'+kind+'Review').classList.toggle('hidden',!x.review);$('#'+kind+'Media').closest('section').querySelector('.reference-info').open=false;
}
function openImage(x){$('#viewerTitle').textContent=x.name;$('#viewerImage').src=media(x);$('#viewerImage').alt='Imagem original enviada para '+x.name;$('#imageViewport').classList.remove('zoomed');$('#imageZoom').textContent='Ampliar';$('#imageViewport').scrollTop=0;$('#imageViewport').scrollLeft=0;$('#imageDialog').showModal();}
function renderDetailTab(tab){const x=ex(currentDetail);$$('[data-detail-tab]').forEach(b=>{const on=b.dataset.detailTab===tab;b.classList.toggle('active',on);b.setAttribute('aria-selected',String(on));});const panel=$('#detailPanel');if(tab==='steps')panel.innerHTML=`<ol class="number-steps">${x.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol>`;else if(tab==='muscles'||tab==='tips')panel.innerHTML=`<p class="detail-panel-copy">${esc(x[tab])}</p>`;else{const ids=x.variants||[];panel.innerHTML=ids.length?`<div class="variant-list">${ids.map(id=>{const v=ex(id);return `<button data-variant="${id}">${esc(v.name)}<small>${esc(v.sub)}</small></button>`;}).join('')}</div>`:'<p class="subtle">Sem variações adicionais neste exercício.</p>';$$('[data-variant]').forEach(b=>b.onclick=()=>openDetail(b.dataset.variant,detailOrigin));}}
function updateFavorite(){const on=state.favorites.includes(currentDetail),b=$('#favoriteBtn');b.textContent=on?'♥':'♡';b.classList.toggle('favorite-on',on);b.setAttribute('aria-pressed',String(on));b.setAttribute('aria-label',on?'Remover dos favoritos':'Adicionar aos favoritos');}
function updateDetailPlan(){$('#detailPlan').textContent=todayPlan().includes(currentDetail)?'✓ Na minha rotina':'+ Minha rotina';}
function openDetail(id,origin='exercises'){currentDetail=id;detailOrigin=origin;const x=ex(id);$('#detailTitle').textContent=x.name;$('#detailSub').textContent=x.sub;$('#detailReps').textContent=x.reps;$('#detailSets').textContent=x.sets;$('#detailTime').textContent=x.time;setMedia('detail',x);renderDetailTab('steps');updateFavorite();updateDetailPlan();showScreen('detail');}
function initialTarget(x){return x.hold||parseInt(x.reps)||10;}
function startSession(ids,task='custom',replace=false){ids=[...new Set(ids.filter(id=>IDS.includes(id)))];if(!ids.length){openRoutine();return;}const d=state.sessionDraft;if(d&&!replace){if(d.task===task&&d.ids.join()===ids.join()){showScreen('session');return;}pendingSession={ids,task};$('#switchDialog').showModal();return;}pauseMedia();if(!commit(()=>state.sessionDraft={id:'session-'+Date.now(),ids,index:0,task,target:initialTarget(ex(ids[0])),regionBefore:state.painRegion,started:Date.now(),elapsed:0}))return;showScreen('session');}
function renderSession(){if(!state.sessionDraft){showScreen('home');openRoutine();return;}const d=state.sessionDraft,x=ex(d.ids[d.index]);$('#sessionLabel').textContent={morning:'Rotina da manhã',day:'Pausas na cadeira',core:'Core e fortalecimento',walk:'Caminhada',custom:d.ids.length===1?'Exercício individual':'Minha rotina'}[d.task];$('#sessionCount').textContent=`${d.index+1} / ${d.ids.length}`;$('#sessionProgress').value=d.index/d.ids.length*100;$('#sessionExerciseTitle').textContent=x.name;$('#sessionExerciseSub').textContent=x.sub;setMedia('session',x);$('#sessionHint').textContent=x.steps.slice(0,2).join(' ');$('#repUnit').textContent=x.hold?'tempo restante':'repetições • ajuste sua meta';$('#timerPlay').classList.toggle('hidden',!x.hold);$('#sessionNext').textContent=d.index===d.ids.length-1?'Concluir e arquivar ✓':'Concluir e próximo →';renderTarget();}
function elapsed(){return (state.sessionDraft?.elapsed||0)+(timerStart!==null?(performance.now()-timerStart)/1000:0);}
function fmt(n){n=Math.max(0,Math.floor(n));return `${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`;}
function renderTarget(){const d=state.sessionDraft;if(!d)return;const x=ex(d.ids[d.index]);$('#repCount').textContent=x.hold?fmt(Math.max(0,Math.ceil(d.target-elapsed()))):d.target;$('#timerStatus').textContent=x.hold?`Meta: ${fmt(d.target)} • ${timerStart!==null?'Em andamento':elapsed()>=d.target?'Tempo concluído':'Cronômetro pausado'}`:'';$('#timerPlay').textContent=timerStart!==null?'Pausar cronômetro':elapsed()>=d.target?'Reiniciar cronômetro':'Iniciar cronômetro';}
function pauseTimer(){if(timerStart!==null&&state.sessionDraft){state.sessionDraft.elapsed=Math.min(state.sessionDraft.target,elapsed());timerStart=null;save();renderTarget();}}
function toggleTimer(){const d=state.sessionDraft;if(!d)return;if(timerStart!==null){pauseTimer();return;}if(d.elapsed>=d.target)d.elapsed=0;timerStart=performance.now();renderTarget();speak('Cronômetro iniciado.');}
setInterval(()=>{if(timerStart===null)return;const d=state.sessionDraft;if(elapsed()>=d.target){pauseTimer();speak('Tempo concluído.');}renderTarget();},250);
function changeTarget(direction){const d=state.sessionDraft;if(!d)return;pauseTimer();let step=ex(d.ids[d.index]).hold?(d.target>=60?30:5):1;commit(()=>{d.target=Math.min(3600,Math.max(1,d.target+direction*step));d.elapsed=Math.min(d.elapsed,d.target);});renderTarget();}
function completeSessionExercise(){const d=state.sessionDraft;if(!d)return;pauseMedia();const id='guided-'+d.id+'-'+d.index,x=ex(d.ids[d.index]);if(!state.records.some(r=>r.id===id)&&!commit(()=>state.records.push({id,exerciseId:x.id,date:new Date().toISOString(),localDate:MotionStore.localDay(),source:'guided',sessionId:d.id,reps:x.hold?null:d.target,seconds:x.hold?d.target:null,sets:null,note:''})))return;
 if(d.index<d.ids.length-1){if(!commit(()=>{d.index++;d.target=initialTarget(ex(d.ids[d.index]));d.elapsed=0;}))return;renderSession();speak('Próximo exercício: '+ex(d.ids[d.index]).name+'.');toast('Exercício arquivado.');}else{$('#painAfter').value=state.dailyNotes[MotionStore.localDay()]?.pain??state.sessions.at(-1)?.pain??0;$('#painValue').textContent=$('#painAfter').value+' / 10';$('#regionAfter').value=String(state.painRegion??d.regionBefore??-1);$('#finishDialog').showModal();}}
function finishSession(withSymptoms=true){const d=state.sessionDraft;if(!d)return;const region=Number($('#regionAfter').value),pain=Number($('#painAfter').value),day=MotionStore.localDay();if(!MotionStore.regionOK(region)||pain<0||pain>10)return;
 if(!commit(()=>{if(withSymptoms&&!state.sessions.some(s=>s.id===d.id)){state.sessions.push({id:d.id,date:new Date().toISOString(),localDate:day,pain,region,regionBefore:d.regionBefore,centralized:d.regionBefore!==null&&region<d.regionBefore,task:d.task,exercises:[...new Set(state.records.filter(r=>r.sessionId===d.id).map(r=>r.exerciseId))],duration:Math.round((Date.now()-d.started)/1000)});state.painRegion=region;}if(d.task!=='custom')state.doneTasks[day]=[...new Set([...(state.doneTasks[day]||[]),d.task])];state.sessionDraft=null;}))return;$('#finishDialog').close();showScreen('home');toast('Sessão arquivada no seu histórico.');}
function openRecord(exerciseId='prone',day=MotionStore.localDay(),recordId=null){pauseMedia();editingRecord=recordId;const r=state.records.find(x=>x.id===recordId),date=r?new Date(r.date):new Date();$('#recordTitle').textContent=r?'Editar registro':'Registrar exercício';$('#recordExercise').value=r?.exerciseId||exerciseId;$('#recordDay').value=r?.localDate||day;$('#recordDay').max=MotionStore.localDay();$('#recordTime').value=`${String(date.getHours()).padStart(2,'0')}:${String(date.getMinutes()).padStart(2,'0')}`;for(const field of ['Sets','Reps','Seconds'])$('#record'+field).value=r?.[field.toLowerCase()]??'';$('#recordNote').value=r?.note||'';$('#deleteRecord').classList.toggle('hidden',!r);$('#recordDialog').showModal();}
function syncSession(sessionId){if(!sessionId)return;const s=state.sessions.find(s=>s.id===sessionId);if(s)s.exercises=[...new Set(state.records.filter(r=>r.sessionId===sessionId).map(r=>r.exerciseId))];}
function saveRecord(){const day=$('#recordDay').value,time=$('#recordTime').value,exerciseId=$('#recordExercise').value;if(!MotionStore.dateOK(day)||day>MotionStore.localDay()||!/^([01]\d|2[0-3]):[0-5]\d$/.test(time)||!IDS.includes(exerciseId)){toast('Confira o dia, o horário e o exercício.');return;}
 let quantities={};for(const [field,max] of [['Sets',999],['Reps',9999],['Seconds',86400]]){const value=$('#record'+field).value;const n=value===''?null:Number(value);if(n!==null&&(!Number.isInteger(n)||n<1||n>max)){toast('Informe quantidades inteiras válidas ou deixe em branco.');return;}quantities[field.toLowerCase()]=n;}
 const old=state.records.find(r=>r.id===editingRecord),r={id:old?.id||uid(),exerciseId,date:new Date(day+'T'+time+':00').toISOString(),localDate:day,source:old?.source||'manual',sessionId:old?.sessionId||null,...quantities,note:$('#recordNote').value.trim()};
 if(!commit(()=>{if(old)state.records=state.records.map(x=>x.id===old.id?r:x);else state.records.push(r);syncSession(r.sessionId);} ))return;$('#recordDialog').close();archiveDay=day;calendarDate=new Date(day+'T12:00:00');refreshScreen();toast('Registro salvo no dia '+new Date(day+'T12:00:00').toLocaleDateString('pt-BR')+'.');}
function deleteRecord(){const record=state.records.find(r=>r.id===editingRecord);if(!record)return;if(!commit(()=>{state.records=state.records.filter(r=>r.id!==record.id);syncSession(record.sessionId);} ))return;$('#recordDialog').close();refreshScreen();toast('Registro excluído.',()=>{if(commit(()=>{state.records.push(record);syncSession(record.sessionId);})){refreshScreen();toast('Registro restaurado.');}});}
function openDayNote(day){noteDay=day;const n=state.dailyNotes[day];$('#dayNoteTitle').textContent=longDate(day);$('#dayPain').value=n?.pain??'';$('#dayRegion').value=n?.region??'';$('#dayText').value=n?.text||'';$('#dayNoteDialog').showModal();}
function saveDayNote(){const pain=$('#dayPain').value,region=$('#dayRegion').value,n={pain:pain===''?null:Number(pain),region:region===''?null:Number(region),text:$('#dayText').value.trim()};if(!commit(()=>state.dailyNotes[noteDay]=n))return;$('#dayNoteDialog').close();refreshScreen();toast('Anotação salva.');}
function describeRecord(r){const parts=[];if(r.sets!==null)parts.push(`${r.sets} série${r.sets===1?'':'s'}`);if(r.reps!==null)parts.push(`${r.reps} repetições`);if(r.seconds!==null)parts.push(fmt(r.seconds));if(!parts.length)parts.push('Execução registrada');if(r.source==='legacy')parts.push('sessão anterior');return parts.join(' · ');}
function renderArchive(){const year=calendarDate.getFullYear(),month=calendarDate.getMonth(),first=new Date(year,month,1),days=new Date(year,month+1,0).getDate(),today=MotionStore.localDay(),marked=new Set([...state.records.map(r=>r.localDate),...state.sessions.map(s=>s.localDate),...Object.entries(state.dailyNotes).filter(([,n])=>n.text||n.pain!==null||n.region!==null).map(([d])=>d)]);
 $('#calendarMonth').textContent=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(first);$('#monthNext').disabled=year===new Date().getFullYear()&&month===new Date().getMonth();$('#calendarDays').innerHTML=Array(first.getDay()).fill('<span></span>').join('')+Array.from({length:days},(_,i)=>{const day=MotionStore.localDay(new Date(year,month,i+1));return `<button data-archive-day="${day}" class="${day===archiveDay?'selected ':''}${day===today?'is-today ':''}${marked.has(day)?'has-record':''}" ${day>today?'disabled':''} aria-label="${esc(longDate(day))}${marked.has(day)?', com registro':''}" aria-pressed="${day===archiveDay}">${i+1}</button>`;}).join('');$$('[data-archive-day]').forEach(b=>b.onclick=()=>{archiveDay=b.dataset.archiveDay;renderArchive();});
 $('#archiveDayTitle').textContent=archiveDay===today?'Hoje, '+longDate(archiveDay):longDate(archiveDay);const records=dayRecords(archiveDay).sort((a,b)=>a.date.localeCompare(b.date)),sessions=state.sessions.filter(s=>s.localDate===archiveDay),plan=state.dailyPlans[archiveDay],done=new Set(records.map(r=>r.exerciseId));$('#archiveSummary').textContent=`${done.size} exercício${done.size===1?'':'s'} · ${records.length} execução${records.length===1?'':'s'}${plan?.length?' · '+plan.filter(id=>done.has(id)).length+'/'+plan.length+' da rotina':''}`;
 $('#archiveEntries').innerHTML=records.length?records.map(r=>`<button class="archive-entry" data-record="${esc(r.id)}"><span class="entry-time">${timeLabel(r.date)}</span><div><h3>${esc(ex(r.exerciseId).name)}</h3><p>${esc(describeRecord(r))}</p>${r.note?`<span class="entry-note">${esc(r.note)}</span>`:''}</div><span aria-hidden="true">›</span></button>`).join(''):'<div class="empty-state"><h3>Nenhum exercício neste dia</h3><p>Os exercícios concluídos aparecerão aqui. Você também pode adicionar uma execução que esqueceu de registrar.</p></div>';$$('[data-record]').forEach(b=>b.onclick=()=>openRecord('prone',archiveDay,b.dataset.record));
 const note=state.dailyNotes[archiveDay],hasNote=note&&(note.text||note.pain!==null||note.region!==null);$('#archiveNote').classList.toggle('hidden',!hasNote&&!sessions.length);$('#archiveNote').innerHTML='<h3>Resumo do dia</h3>'+(hasNote?`${note.pain!==null?`<small>Dor ${note.pain}/10</small>`:''}${note.region!==null?`<small>${esc(regionLabel(note.region))}</small>`:''}${note.text?`<p>${esc(note.text)}</p>`:''}`:'')+sessions.map(s=>`<small>Sessão às ${timeLabel(s.date)} · dor ${s.pain}/10 · ${esc(regionLabel(s.region))}</small>`).join('');}

function renderMap(){for(const r of $$('input[name=painRegion]'))r.checked=Number(r.value)===state.painRegion;const glow=$('#mapGlow');glow.classList.toggle('none',state.painRegion===null||state.painRegion===-1);$$('[data-region]').forEach(b=>{b.classList.toggle('selected',Number(b.dataset.region)===state.painRegion);b.setAttribute('aria-pressed',String(Number(b.dataset.region)===state.painRegion));});const img=$('.map-human');img.src=mapView==='back'?'./posters/pain_map_realistic.jpg':`./posters/map-${mapView}.svg`;img.alt=mapView==='back'?'Vista posterior do corpo com trajeto aproximado dos sintomas':mapView==='front'?'Vista frontal do corpo':'Vista do lado esquerdo do corpo';$('#mapGlow').dataset.view=mapView;$$('[data-map-view]').forEach(b=>{b.classList.toggle('active',b.dataset.mapView===mapView);b.setAttribute('aria-pressed',String(b.dataset.mapView===mapView));});requestAnimationFrame(positionMapMarkers);}
function regionLabel(n){return REGIONS[n+1]||'Não informado';}

function positionMapMarkers(){const img=$('.map-human'),wrap=$('.map-human-wrap');if(!img.naturalWidth)return;const w=wrap.clientWidth,h=wrap.clientHeight,scale=Math.min(w/img.naturalWidth,h/img.naturalHeight),rw=img.naturalWidth*scale,rh=img.naturalHeight*scale,left=(w-rw)/2,top=(h-rh)/2;const xy=mapView==='back'?[[.60,.42],[.73,.53],[.73,.69],[.73,.81],[.71,.94]]:mapView==='front'?[[.51,.46],[.59,.54],[.60,.65],[.61,.79],[.61,.94]]:[[.40,.46],[.46,.54],[.48,.65],[.47,.79],[.48,.93]];$$('[data-region]').forEach((b,i)=>{b.style.left=(left+xy[i][0]*rw)+'px';b.style.top=(top+xy[i][1]*rh)+'px';});}

function icon(name){const paths={history:'M4 4h16v17H4zM4 9h16M8 2v4M16 2v4M8 13h.1M12 13h.1M16 13h.1M8 17h.1M12 17h.1',info:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20M12 11v6M12 7v.2',export:'M12 3v12M7 10l5 5 5-5M4 17v4h16v-4',home:'M3 10 12 3l9 7v10h-6v-7H9v7H3Z',exercises:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',session:'M9 2h6M12 2v3M18 6l2-2M12 9v5l3 2M12 5a8 8 0 1 0 0 16 8 8 0 0 0 0-16',map:'M12 22s8-8 8-13a8 8 0 0 0-16 0c0 5 8 13 8 13zM12 6a3 3 0 1 0 0 6 3 3 0 0 0 0-6',progress:'M4 20V13M10 20V7M16 20V3M22 20H2',sun:'M12 7a5 5 0 1 0 0 10 5 5 0 0 0 0-10M12 1v3M12 20v3M1 12h3M20 12h3M4 4l2 2M18 18l2 2M20 4l-2 2M6 18l-2 2',chair:'M6 3v10h12V3M4 13h16v4H4zM6 17v5M18 17v5',core:'M3 8v8M7 5v14M7 12h10M17 5v14M21 8v8',walk:'M13 3a2 2 0 1 0 0 4 2 2 0 0 0 0-4M12 8l-3 5-4 1M12 8l4 4 4 1M11 13l3 4 1 5M11 13l-3 8'};return `<svg class="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.walk}"/></svg>`;}
function renderProgress(){const s=state.sessions;$('#pStreak').textContent=`${calcStreak()} dias`;$('#pSessions').textContent=new Set(state.records.filter(r=>r.sessionId).map(r=>r.sessionId)).size;$('#pCentral').textContent=s.filter(x=>x.centralized&&x.regionBefore!==null).length;$('#progressDiaryStats').textContent=`${state.records.length} execuções arquivadas em ${new Set(state.records.map(r=>r.localDate)).size} dias.`;
 const painPoints=[...s.map(x=>({day:x.localDate,pain:x.pain,region:x.region})),...Object.entries(state.dailyNotes).map(([day,n])=>({day,...n}))].sort((a,b)=>a.day.localeCompare(b.day));drawChart($('#painChart'),painPoints.filter(x=>x.pain!==null).map(x=>x.pain),0,10,['10','5','0'],false);drawChart($('#regionChart'),painPoints.filter(x=>x.region!==null).map(x=>x.region),-1,4,['Sem dor','Lombar','Nádega','Coxa','Pant.','Pé'],true);
 $('#historyList').innerHTML=s.length?[...s].reverse().slice(0,30).map(x=>{let msg=x.regionBefore===null?'sem comparação':x.region<x.regionBefore?'↑ recuou':x.region>x.regionBefore?'↓ avançou':'• estável';let cls=x.regionBefore===null||x.region===x.regionBefore?'history-neutral':x.centralized?'history-good':'history-bad';return `<button class="history-item" data-session-day="${x.localDate}"><div><b>${new Date(x.localDate+'T12:00:00').toLocaleDateString('pt-BR')}</b><br><small>Dor ${x.pain}/10 • ${esc(regionLabel(x.region))}</small></div><span class="${cls}">${msg}</span></button>`;}).join(''):'<p class="subtle">Registre os sintomas ao concluir uma sessão para acompanhar a comparação. Seus exercícios estão na aba Histórico.</p>';$$('[data-session-day]').forEach(b=>b.onclick=()=>{archiveDay=b.dataset.sessionDay;calendarDate=new Date(archiveDay+'T12:00:00');showScreen('history');});}
function drawChart(c,vals,min,max,labels,distal){const ctx=c.getContext('2d'),w=c.clientWidth||320,h=220,dpr=Math.min(devicePixelRatio||1,3),css=getComputedStyle(document.body),color=v=>css.getPropertyValue(v).trim();c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.fillStyle=color('--panel');ctx.fillRect(0,0,w,h);const top=20,bottom=184,left=54,right=w-16;ctx.font='11px system-ui';labels.forEach((l,i)=>{const y=top+i*(bottom-top)/(labels.length-1);ctx.strokeStyle=color('--line');ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(right,y);ctx.stroke();ctx.fillStyle=color('--muted');ctx.fillText(l,3,y+4);});const a=vals.slice(-20);if(!a.length){ctx.fillText('Nenhum registro.',left+12,110);return;}const points=a.map((v,i)=>({x:a.length===1?(left+right)/2:left+(right-left)*i/(a.length-1),y:top+(bottom-top)*(distal?(v-min)/(max-min):1-(v-min)/(max-min))}));ctx.strokeStyle=color('--blue');ctx.lineWidth=2.4;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.fillStyle=color('--blue');for(const p of points){ctx.beginPath();ctx.arc(p.x,p.y,3.4,0,2*Math.PI);ctx.fill();}ctx.fillStyle=color('--muted');ctx.fillText(`${a.length} registros recentes`,left,207);}
function download(filename,mime,content){if(window.MotionNative){window.MotionNative.exportText(filename,mime,content);return;}const url=URL.createObjectURL(new Blob([content],{type:mime}));let a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportCSV(){const rows=[['tipo','data_hora','dia_local','exercicio_id','exercicio','series','repeticoes','tempo_segundos','observacao','origem','sessao_id','dor','regiao_antes','regiao_depois','recuou','rotina','exercicios_sessao']];
 [...state.records].sort((a,b)=>a.localDate.localeCompare(b.localDate)||a.date.localeCompare(b.date)).forEach(r=>rows.push(['exercicio',r.date,r.localDate,r.exerciseId,ex(r.exerciseId).name,r.sets??'',r.reps??'',r.seconds??'',r.note,r.source,r.sessionId||'','','','','','','']));
 Object.entries(state.dailyNotes).sort(([a],[b])=>a.localeCompare(b)).forEach(([day,n])=>rows.push(['resumo_dia','',day,'','','','','',n.text,'','',''+(n.pain??''),'',n.region??'','','','']));
 state.sessions.forEach(s=>rows.push(['sintomas_sessao',s.date,s.localDate,'','','','',s.duration,'','',s.id,s.pain,s.regionBefore??'',s.region,s.centralized,s.task,s.exercises.join('|')]));
 const csvCell=v=>{let t=String(v);if(/^\s*[=+@-]/.test(t))t="'"+t;return '"'+t.replace(/"/g,'""')+'"';};download('l5s1-diario.csv','text/csv','\ufeff'+rows.map(r=>r.map(csvCell).join(';')).join('\r\n'));}
function backup(){pauseTimer();download('l5s1-backup.json','application/json',storageProblem?storedRaw:JSON.stringify(state));}
function importBackup(f){if(f.size>5*1024*1024){toast('O backup deve ter no máximo 5 MB.');return;}let reader=new FileReader();reader.onload=()=>{try{const raw=JSON.parse(reader.result);if(!Array.isArray(raw.sessions))throw Error('O arquivo não é um backup do aplicativo.');const next=MotionStore.normalize(raw,IDS),previous=state,issue=storageProblem;pauseMedia();state=next;storageProblem='';if(!save()){state=previous;storageProblem=issue;return;}applyTheme();$('#settingsDialog').close();showScreen('home');toast('Backup importado com sucesso.');}catch(e){toast(e.message||'Arquivo inválido.');}finally{$('#importInput').value='';}};reader.onerror=()=>toast('Não foi possível ler o arquivo.');reader.readAsText(f);}
function showSettings(){$('#startDate').value=state.settings.startDate;$('#startDate').max=MotionStore.localDay();$('#morningTime').value=state.settings.morningTime;$('#coreTime').value=state.settings.coreTime;$('#voiceEnabled').checked=state.settings.voice;$('#darkMode').checked=state.settings.dark;$('#settingsDialog').showModal();}
function info(title,text){$('#infoTitle').textContent=title;$('#infoContent').textContent=text;$('#infoDialog').showModal();}
for(const kind of ['detail','session']){const v=$('#'+kind+'Video');v.addEventListener('error',()=>{if(v.getAttribute('src'))toast('Vídeo indisponível. Consulte a execução escrita.');});$('#'+kind+'Speed').onchange=e=>v.playbackRate=Number(e.target.value);}
$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
$$('.bottom-nav button').forEach(b=>{b.onclick=()=>showScreen(b.dataset.nav);b.querySelector('span').innerHTML=icon(b.dataset.nav);});$('.brand-icon').innerHTML=icon('walk');
$('#settingsBtn').onclick=showSettings;$('#saveSettings').onclick=()=>{const date=$('#startDate').value;if(!MotionStore.dateOK(date)||date>MotionStore.localDay()){toast('Informe uma data de início válida, até hoje.');return;}if(!commit(()=>state.settings={startDate:date,morningTime:$('#morningTime').value||'08:00',coreTime:$('#coreTime').value||'19:00',voice:$('#voiceEnabled').checked,dark:$('#darkMode').checked}))return;applyTheme();$('#settingsDialog').close();refreshScreen();toast('Ajustes salvos.');};$('#backupBtn').onclick=backup;$('#settingsExport').onclick=exportCSV;$('#importInput').onchange=e=>e.target.files[0]&&importBackup(e.target.files[0]);$('#settingsAbout').onclick=()=>info('L5-S1 Motion Pro 7.0','Diário pessoal de exercícios, com 19 imagens e 2 vídeos enviados por você.\n\nAs demonstrações 3D anteriores foram substituídas. Fotos permanecem estáticas; vídeos mostram movimento gravado, sem zoom artificial.\n\nAs referências fornecidas não passaram por validação clínica. Quatro imagens têm dúvidas visuais sinalizadas: press-up, prancha lateral completa, ponte com marcha e prancha lateral com joelhos.\n\nAs rotinas e quantidades da versão anterior estão disponíveis como referência. Este diário não escolhe um tratamento nem ajusta exercícios automaticamente.\n\nHistórico, favoritos, mapas, voz e backups foram preservados. Dados locais não se sincronizam entre o APK e o site; use o backup para transferir.');
$('#homeStartSession').onclick=()=>{if(state.sessionDraft){showScreen('session');return;}const done=new Set(dayRecords(MotionStore.localDay()).map(r=>r.exerciseId)),plan=todayPlan(),pending=plan.filter(id=>!done.has(id));startSession(pending.length?pending:plan);};$('#homeMapBtn').onclick=()=>showScreen('map');$('#homeHistoryBtn').onclick=()=>{archiveDay=MotionStore.localDay();calendarDate=new Date(archiveDay+'T12:00:00');showScreen('history');};$('#homeQuickAdd').onclick=()=>openRecord(todayPlan()[0]||'prone');$('#editRoutine').onclick=openRoutine;$('#homeDayNote').onclick=$('#todayNoteSummary').onclick=()=>openDayNote(MotionStore.localDay());
$('#routineSearch').oninput=renderRoutine;$('#saveRoutine').onclick=()=>{const day=MotionStore.localDay();if(!commit(()=>{state.routine=[...routineDraft];state.dailyPlans[day]=[...routineDraft];}))return;$('#routineDialog').close();refreshScreen();toast('Rotina salva para hoje e os próximos dias.');};$('#exerciseSearch').oninput=renderExercises;
$('#detailBack').onclick=()=>showScreen(detailOrigin);$('#detailStart').onclick=()=>startSession([currentDetail]);$('#detailLog').onclick=()=>openRecord(currentDetail);$('#detailPlan').onclick=()=>togglePlan(currentDetail);$('#favoriteBtn').onclick=()=>{if(commit(()=>state.favorites=state.favorites.includes(currentDetail)?state.favorites.filter(x=>x!==currentDetail):[...state.favorites,currentDetail]))updateFavorite();};$$('[data-detail-tab]').forEach(b=>b.onclick=()=>renderDetailTab(b.dataset.detailTab));
$('#sessionBack').onclick=()=>showScreen('home');$('#repMinus').onclick=()=>changeTarget(-1);$('#repPlus').onclick=()=>changeTarget(1);$('#timerPlay').onclick=toggleTimer;$('#sessionNext').onclick=completeSessionExercise;$('#resumeDraft').onclick=()=>{$('#switchDialog').close();pendingSession=null;showScreen('session');};$('#replaceDraft').onclick=()=>{const next=pendingSession;$('#switchDialog').close();pendingSession=null;if(next)startSession(next.ids,next.task,true);};
$('#saveRecord').onclick=saveRecord;$('#deleteRecord').onclick=deleteRecord;$('#saveDayNote').onclick=saveDayNote;$('#archiveDayNote').onclick=()=>openDayNote(archiveDay);$('#archiveAdd').onclick=()=>openRecord(todayPlan()[0]||'prone',archiveDay);$('#monthPrev').onclick=()=>{calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()-1,1,12);renderArchive();};$('#monthNext').onclick=()=>{calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()+1,1,12);renderArchive();};$('#historyToday').onclick=()=>{archiveDay=MotionStore.localDay();calendarDate=new Date(archiveDay+'T12:00:00');renderArchive();};
$$('input[name=painRegion]').forEach(r=>r.onchange=()=>{if(commit(()=>state.painRegion=Number(r.value)))renderMap();});$$('[data-region]').forEach(b=>b.onclick=()=>{if(commit(()=>state.painRegion=Number(b.dataset.region)))renderMap();});$$('[data-map-view]').forEach(b=>b.onclick=()=>{mapView=b.dataset.mapView;renderMap();});$('#clearPain').onclick=()=>{if(commit(()=>state.painRegion=null))renderMap();};$('#mapInfo').onclick=()=>info('Como registrar os sintomas','Selecione a região mais distante em que sente dor ou formigamento. O mapa ilustra um trajeto aproximado e não estabelece diagnóstico. A comparação de regiões é registrada somente quando há uma região anterior. Use os exercícios conforme sua orientação profissional.');$('#exportBtn').onclick=exportCSV;$('#mapInfo').innerHTML=icon('info');$('#mapInfo').setAttribute('aria-label','Como usar o mapa da dor');$('#exportBtn').innerHTML=icon('export');
$('#painAfter').oninput=e=>$('#painValue').textContent=e.target.value+' / 10';$('#finishSave').onclick=()=>finishSession(true);$('#finishSkip').onclick=()=>finishSession(false);$('#imageZoom').onclick=()=>{const zoom=$('#imageViewport').classList.toggle('zoomed');$('#imageZoom').textContent=zoom?'Ajustar':'Ampliar';};
$('#recordExercise').innerHTML=E.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');$('#dayPain').innerHTML+=[...Array(11)].map((_,i)=>`<option value="${i}">${i} / 10</option>`).join('');for(const name of ['dayRegion','regionAfter'])$('#'+name).innerHTML+=REGIONS.map((r,i)=>`<option value="${i-1}">${r}</option>`).join('');
window.onpopstate=e=>{const open=$('dialog[open]');if(open)open.close();showScreen(e.state?.screen||'home',false);};window.appPause=pauseMedia;window.appBack=()=>{const open=$('dialog[open]');if(open){open.close();return true;}if(currentScreen!=='home'){showScreen(currentScreen==='detail'?detailOrigin:'home');return true;}return false;};window.nativeExportDone=ok=>toast(ok?'Arquivo salvo.':'Exportação cancelada.');
document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseMedia();else{ensureToday();refreshScreen();}});window.addEventListener('pagehide',pauseMedia);let resizeHandle;window.addEventListener('resize',()=>{clearTimeout(resizeHandle);resizeHandle=setTimeout(()=>{if(currentScreen==='progress')renderProgress();positionMapMarkers();},120);});$('.map-human').addEventListener('load',positionMapMarkers);
applyTheme();renderFilters();renderHome();renderExercises();renderMap();history.replaceState({screen:'home'},'','#home');$('#app').dataset.screen='home';
if(storageProblem)info('Não foi possível ler os dados','O arquivo local original foi preservado. Use Ajustes → Exportar backup completo para recuperá-lo, ou importe um backup válido. Não foram apagados registros.');
// Refresh at local midnight without inventing completions or modifying earlier days.
setInterval(()=>{if(!document.hidden&&currentScreen==='home'&&!$('dialog[open]'))renderHome();},60000);
if('serviceWorker'in navigator&&['https:','http:'].includes(location.protocol))navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
