'use strict';
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];
const KEY='l5s1-studio-v4',IDS=E.map(x=>x.id),REGIONS=['Sem sintomas','Apenas lombar','Nádega','Coxa','Panturrilha','Pé / dedos'];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=load(),currentDetail='pressup',activeFilter='Todos',currentScreen='home',mapView='back',timerStart=null,toastHandle;
function load(){try{return MotionStore.normalize(JSON.parse(localStorage.getItem(KEY)||'{}'),IDS);}catch(e){return MotionStore.defaults();}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch(e){toast('Não foi possível salvar. Exporte um backup antes de sair.');return false;}}
function ex(id){return E.find(x=>x.id===id)||E[0];}
function poster(x){return `./posters/${x.poster}`;}
function media(x){return `./media/${x.video}`;}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('visible');clearTimeout(toastHandle);toastHandle=setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
function speak(t){if(!state.settings.voice)return;if(window.MotionNative){window.MotionNative.speak(t);return;}if(!('speechSynthesis'in window))return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='pt-BR';u.rate=.95;speechSynthesis.speak(u);}
function stopVoice(){if(window.MotionNative)window.MotionNative.stopSpeech();else if('speechSynthesis'in window)speechSynthesis.cancel();}
function applyTheme(){document.body.classList.toggle('light',!state.settings.dark);}
function daysSinceStart(){const start=new Date(state.settings.startDate+'T00:00:00'),today=new Date(MotionStore.localDay()+'T00:00:00');return Math.max(0,Math.round((today-start)/86400000));}
function week(){return Math.min(8,Math.floor(daysSinceStart()/7)+1);}
function weekPct(){return daysSinceStart()>=56?100:Math.round(((daysSinceStart()%7)+1)/7*100);}
function calcStreak(){const dates=new Set(state.sessions.map(s=>s.localDate));let n=0,d=new Date();if(!dates.has(MotionStore.localDay(d)))d.setDate(d.getDate()-1);while(dates.has(MotionStore.localDay(d))){n++;d.setDate(d.getDate()-1);}return n;}
function pauseMedia(){for(const v of $$('video'))v.pause();pauseTimer();stopVoice();}
function showScreen(name,push=true){if(!['home','exercises','session','map','progress','detail'].includes(name))name='home';pauseMedia();currentScreen=name;$('#app').dataset.screen=name;$$('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===name));$$('.bottom-nav button').forEach(b=>{const active=b.dataset.nav===name||(name==='detail'&&b.dataset.nav==='exercises');b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});
 if(push&&history.state?.screen!==name)history.pushState({screen:name},'',`#${name}`);
 if(name==='home')renderHome();if(name==='exercises')renderExercises();if(name==='session')renderSession();if(name==='map')renderMap();if(name==='progress')renderProgress();window.scrollTo(0,0);
}
const TASKS=[['sun','Manhã – Centralização','8–10 min','morning'],['chair','Durante o dia – Cadeira','5–7 min','day'],['core','Core e fortalecimento','12–15 min','core'],['walk','Caminhada','10–20 min','walk']];
function renderHome(){const w=week(),p=weekPct();$('#weekTitle').textContent=`Semana ${w} de 8`;$('#weekPct').textContent=`${p}%`;$('#progressRing').style.background=`conic-gradient(var(--green) 0deg ${p*3.6}deg,#173046 ${p*3.6}deg 360deg)`;$('#todayWeekday').textContent=new Intl.DateTimeFormat('pt-BR',{weekday:'long'}).format(new Date());$('#streakHome').textContent=calcStreak();$('#sessionsHome').textContent=state.sessions.length;const recent=state.sessions.slice(-8);$('#painHome').textContent=recent.length?`${(recent.reduce((a,s)=>a+s.pain,0)/recent.length).toFixed(1)}/10`:'—';$('#homeStartSession').textContent=state.sessionDraft?'▶ Continuar sessão guiada':'▶ Iniciar sessão guiada';
 const day=MotionStore.localDay();$('#todayTasks').innerHTML=TASKS.map(([ic,t,d,k])=>`<button class="task-card" data-task="${k}"><div class="task-icon">${icon(ic)}</div><div><div class="task-title">${t}</div><div class="task-duration">${k==='morning'?state.settings.morningTime+' • ':k==='core'?state.settings.coreTime+' • ':''}${d}</div></div><div class="task-check ${state.doneTasks[day]?.includes(k)?'done':''}" aria-label="${state.doneTasks[day]?.includes(k)?'Concluída':'Pendente'}"></div></button>`).join('');$$('[data-task]').forEach(b=>b.onclick=()=>startSession(PRESETS[b.dataset.task],b.dataset.task));
}
function renderFilters(){const cats=['Todos','Centralização','Neural','Core','Cadeira','Atividade','Favoritos'];$('#exerciseFilters').innerHTML=cats.map(c=>`<button data-cat="${c}" class="${activeFilter===c?'active':''}" aria-pressed="${activeFilter===c}">${c}</button>`).join('');$$('[data-cat]').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.cat;renderFilters();renderExercises();});}
function renderExercises(){const q=$('#exerciseSearch').value.trim().toLocaleLowerCase('pt-BR');const list=E.filter(x=>(activeFilter==='Todos'||activeFilter===x.cat||(activeFilter==='Favoritos'&&state.favorites.includes(x.id)))&&(!q||(x.name+' '+x.sub).toLocaleLowerCase('pt-BR').includes(q)));
 $('#exerciseList').innerHTML=list.length?list.map(x=>`<button class="exercise-row ${x.id===currentDetail?'selected-row':''}" data-ex="${x.id}"><img class="exercise-thumb" src="${poster(x)}" alt="Posição de ${esc(x.name)}" loading="lazy"><div><h3>${esc(x.name)} ${state.favorites.includes(x.id)?'<span class="favorite-on">♥</span>':''}</h3><p>${esc(x.sub)}</p></div><span class="chev" aria-hidden="true">›</span></button>`).join(''):'<p class="subtle">Nenhum exercício encontrado.</p>';$$('[data-ex]').forEach(b=>b.onclick=()=>openDetail(b.dataset.ex));
}
function setVideo(kind,x){const v=$('#'+kind+'Video');v.pause();v.poster=poster(x);v.src=media(x);v.playbackRate=Number($('#'+kind+'Speed').value);v.load();$('#'+kind+'DemoLabel').textContent=x.hold&&x.id!=='walk'?'Posição sustentada • demonstração 3D':'Demonstração humana em 3D';updatePhase(kind);}
function renderDetailTab(tab){const x=ex(currentDetail);$$('[data-detail-tab]').forEach(b=>{const on=b.dataset.detailTab===tab;b.classList.toggle('active',on);b.setAttribute('aria-selected',String(on));});
 const panel=$('#detailPanel');if(tab==='steps')panel.innerHTML=`<ol id="detailSteps" class="number-steps">${x.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol>`;else if(tab==='muscles'||tab==='tips')panel.innerHTML=`<p class="detail-panel-copy">${esc(x[tab])}</p>`;else{const ids=x.variants||[];panel.innerHTML=ids.length?`<div class="variant-list">${ids.map(id=>{const v=ex(id);return `<button data-variant="${id}">${esc(v.name)}<small>${esc(v.sub)}</small></button>`;}).join('')}</div>`:'<p class="subtle">Sem variações adicionais neste exercício.</p>';$$('[data-variant]').forEach(b=>b.onclick=()=>openDetail(b.dataset.variant));}
}
function updateFavorite(){const on=state.favorites.includes(currentDetail),b=$('#favoriteBtn');b.textContent=on?'♥':'♡';b.classList.toggle('favorite-on',on);b.setAttribute('aria-pressed',String(on));b.setAttribute('aria-label',on?'Remover dos favoritos':'Adicionar aos favoritos');}
function openDetail(id){currentDetail=id;const x=ex(id);$('#detailTitle').textContent=x.name;$('#detailSub').textContent=x.sub;$('#detailReps').textContent=x.reps;$('#detailSets').textContent=x.sets;$('#detailTime').textContent=x.time;setVideo('detail',x);renderDetailTab('steps');updateFavorite();showScreen('detail');}
function initialTarget(x){return x.hold||parseInt(x.reps)||10;}
function startSession(ids,task='custom'){if(!state.sessionDraft||state.sessionDraft.task!==task||state.sessionDraft.ids.join()!==ids.join()){state.sessionDraft={ids:[...ids],index:0,task,target:initialTarget(ex(ids[0])),regionBefore:state.painRegion,started:Date.now(),elapsed:0};save();}showScreen('session');}
function renderSession(){if(!state.sessionDraft){startSession(PRESETS.morning,'morning');return;}const d=state.sessionDraft,x=ex(d.ids[d.index]);$('#sessionLabel').textContent={morning:'☀ Rotina da manhã',day:'Durante o dia – Cadeira',core:'Core e fortalecimento',walk:'Caminhada',custom:'Exercício individual'}[d.task];$('#sessionCount').textContent=`${d.index+1} de ${d.ids.length}`;$('#sessionExerciseTitle').textContent=x.name;$('#sessionExerciseSub').textContent=x.sub;setVideo('session',x);$('#sessionHint').textContent=x.steps.slice(0,2).join(' ');$('#repUnit').textContent=x.hold?'tempo restante':'repetições';$('#timerPlay').classList.toggle('hidden',!x.hold);$('#sessionNext').textContent=d.index===d.ids.length-1?'Concluir e registrar ✓':'Concluir e próximo →';renderTarget();}
function elapsed(){return (state.sessionDraft?.elapsed||0)+(timerStart!==null?(performance.now()-timerStart)/1000:0);}
function renderTarget(){const d=state.sessionDraft;if(!d)return;const x=ex(d.ids[d.index]);$('#repCount').textContent=x.hold?fmt(Math.max(0,Math.ceil(d.target-elapsed()))):d.target;$('#timerStatus').textContent=x.hold?`Meta: ${fmt(d.target)} • ${timerStart!==null?'Em andamento':'Cronômetro independente da demonstração'}`:'';$('#timerPlay').textContent=timerStart!==null?'Pausar cronômetro':elapsed()>=d.target?'Reiniciar cronômetro':'Iniciar cronômetro';}
function pauseTimer(){if(timerStart!==null&&state.sessionDraft){state.sessionDraft.elapsed=Math.min(state.sessionDraft.target,elapsed());timerStart=null;save();renderTarget();}}
function toggleTimer(){const d=state.sessionDraft;if(!d)return;if(timerStart!==null){pauseTimer();return;}if(d.elapsed>=d.target)d.elapsed=0;timerStart=performance.now();renderTarget();speak('Cronômetro iniciado. Respire normalmente.');}
setInterval(()=>{if(timerStart===null)return;const d=state.sessionDraft;if(elapsed()>=d.target){pauseTimer();$('#timerStatus').textContent='Tempo concluído. Continue quando estiver pronto.';speak('Tempo concluído.');}renderTarget();},250);
function changeTarget(direction){const d=state.sessionDraft;if(!d)return;pauseTimer();let step=ex(d.ids[d.index]).hold?(d.target>=60?30:5):1;d.target=Math.min(3600,Math.max(1,d.target+direction*step));d.elapsed=Math.min(d.elapsed,d.target);save();renderTarget();}
function completeSessionExercise(){const d=state.sessionDraft;if(!d)return;pauseMedia();if(d.index<d.ids.length-1){d.index++;d.target=initialTarget(ex(d.ids[d.index]));d.elapsed=0;save();renderSession();speak('Próximo exercício: '+ex(d.ids[d.index]).name+'.');}else{$('#painAfter').value=state.sessions.at(-1)?.pain??4;$('#painValue').textContent=$('#painAfter').value+' / 10';$('#regionAfter').value=String(state.painRegion??d.regionBefore??0);$('#finishDialog').showModal();}}
function finishSession(){const d=state.sessionDraft;if(!d)return;const region=Number($('#regionAfter').value),pain=Number($('#painAfter').value);if(!MotionStore.regionOK(region)||pain<0||pain>10)return;const day=MotionStore.localDay();state.sessions.push({date:new Date().toISOString(),localDate:day,pain,region,regionBefore:d.regionBefore,centralized:d.regionBefore!==null&&region<d.regionBefore,task:d.task,exercises:[...d.ids],duration:Math.round((Date.now()-d.started)/1000)});if(d.task!=='custom')state.doneTasks[day]=[...new Set([...(state.doneTasks[day]||[]),d.task])];state.painRegion=region;state.sessionDraft=null;save();$('#finishDialog').close();showScreen('home');toast('Sessão concluída e registrada.');}
function renderMap(){for(const r of $$('input[name=painRegion]'))r.checked=Number(r.value)===state.painRegion;const glow=$('#mapGlow');glow.classList.toggle('none',state.painRegion===null||state.painRegion===-1);$$('[data-region]').forEach(b=>{b.classList.toggle('selected',Number(b.dataset.region)===state.painRegion);b.setAttribute('aria-pressed',String(Number(b.dataset.region)===state.painRegion));});const img=$('.map-human');img.src=mapView==='back'?'./posters/pain_map_realistic.jpg':`./posters/map-${mapView}.svg`;img.alt=mapView==='back'?'Vista posterior do corpo com trajeto aproximado dos sintomas':mapView==='front'?'Vista frontal do corpo':'Vista do lado esquerdo do corpo';$('#mapGlow').dataset.view=mapView;$$('[data-map-view]').forEach(b=>{b.classList.toggle('active',b.dataset.mapView===mapView);b.setAttribute('aria-pressed',String(b.dataset.mapView===mapView));});requestAnimationFrame(positionMapMarkers);}
function regionLabel(n){return REGIONS[n+1]||'Não informado';}
function renderProgress(){const s=state.sessions;$('#pStreak').textContent=`${calcStreak()} dias`;$('#pSessions').textContent=s.length;$('#pCentral').textContent=s.filter(x=>x.centralized&&x.regionBefore!==null).length;drawChart($('#painChart'),s.map(x=>x.pain),0,10,['10','5','0'],false);drawChart($('#regionChart'),s.map(x=>x.region),-1,4,['Sem dor','Lombar','Nádega','Coxa','Pant.','Pé'],true);$('#historyList').innerHTML=s.length?[...s].reverse().slice(0,30).map(x=>{let msg=x.regionBefore===null?'sem comparação':x.region<x.regionBefore?'↑ recuou':x.region>x.regionBefore?'↓ avançou':'• estável';let cls=x.regionBefore===null||x.region===x.regionBefore?'history-neutral':x.centralized?'history-good':'history-bad';return `<div class="history-item"><div><b>${new Date(x.date).toLocaleDateString('pt-BR')}</b><br><small>Dor ${x.pain}/10 • ${esc(regionLabel(x.region))}</small></div><span class="${cls}">${msg}</span></div>`;}).join(''):'<p class="subtle">Nenhuma sessão registrada ainda.</p>';}
function drawChart(c,vals,min,max,labels,distal){const ctx=c.getContext('2d'),w=c.clientWidth||320,h=220,dpr=Math.min(devicePixelRatio||1,3);c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.fillStyle='#061725';ctx.fillRect(0,0,w,h);const top=20,bottom=184,left=54,right=w-16;ctx.font='11px system-ui';labels.forEach((l,i)=>{const y=top+i*(bottom-top)/(labels.length-1);ctx.strokeStyle='#17384f';ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(right,y);ctx.stroke();ctx.fillStyle='#9db0c2';ctx.fillText(l,3,y+4);});const a=vals.slice(-20);if(!a.length){ctx.fillText('Nenhum registro.',left+12,110);return;}const points=a.map((v,i)=>({x:a.length===1?(left+right)/2:left+(right-left)*i/(a.length-1),y:top+(bottom-top)*(distal?(v-min)/(max-min):1-(v-min)/(max-min))}));ctx.strokeStyle='#21a9ff';ctx.lineWidth=2.8;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.fillStyle='#49bfff';for(const p of points){ctx.beginPath();ctx.arc(p.x,p.y,3.4,0,2*Math.PI);ctx.fill();}ctx.fillStyle='#9db0c2';ctx.fillText(`${a.length} registro${a.length>1?'s':''} recentes`,left,207);}
function download(filename,mime,content){if(window.MotionNative){window.MotionNative.exportText(filename,mime,content);return;}const url=URL.createObjectURL(new Blob([content],{type:mime}));let a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportCSV(){const rows=[['data','dia_local','dor','regiao_antes','regiao_depois','recuou','rotina','exercicios']];state.sessions.forEach(s=>rows.push([s.date,s.localDate,s.pain,s.regionBefore??'',s.region,s.centralized,s.task,s.exercises.join('|')]));download('l5s1-progresso.csv','text/csv','\ufeff'+rows.map(r=>r.join(';')).join('\r\n'));}
function backup(){pauseTimer();download('l5s1-backup.json','application/json',JSON.stringify(state,null,2));}
function importBackup(f){if(f.size>5*1024*1024){toast('O backup deve ter no máximo 5 MB.');return;}let reader=new FileReader();reader.onload=()=>{try{const raw=JSON.parse(reader.result);if(!Array.isArray(raw.sessions))throw Error('O arquivo não é um backup do aplicativo.');const next=MotionStore.normalize(raw,IDS);pauseMedia();state=next;save();applyTheme();$('#settingsDialog').close();showScreen('home');toast('Backup importado com sucesso.');}catch(e){toast(e.message||'Arquivo inválido.');}$('#importInput').value='';};reader.onerror=()=>toast('Não foi possível ler o arquivo.');reader.readAsText(f);}
function showSettings(){$('#startDate').value=state.settings.startDate;$('#startDate').max=MotionStore.localDay();$('#morningTime').value=state.settings.morningTime;$('#coreTime').value=state.settings.coreTime;$('#voiceEnabled').checked=state.settings.voice;$('#darkMode').checked=state.settings.dark;$('#settingsDialog').showModal();}
function info(title,text){$('#infoTitle').textContent=title;$('#infoContent').textContent=text;$('#infoDialog').showModal();}
function fmt(n){n=Math.max(0,Math.floor(n));return `${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`;}
function updatePhase(kind){const v=$('#'+kind+'Video'),x=kind==='detail'?ex(currentDetail):ex(state.sessionDraft?.ids[state.sessionDraft.index]);let phase=x.hold&&x.id!=='walk'?'Sustente a posição e respire normalmente.':(v.currentTime/(v.duration||8))%1<.5?'Execute com controle • observe os apoios.':'Retorne devagar • alterne quando indicado.';$('#'+kind+'Phase').textContent=phase;}
for(const kind of ['detail','session']){const v=$('#'+kind+'Video');$('#'+kind+'PlayOverlay').onclick=async()=>{try{await v.play();}catch(e){toast('Não foi possível reproduzir esta demonstração.');}};v.addEventListener('play',()=>v.parentElement.classList.add('is-playing'));v.addEventListener('pause',()=>v.parentElement.classList.remove('is-playing'));v.addEventListener('timeupdate',()=>updatePhase(kind));v.addEventListener('error',()=>{if(v.getAttribute('src'))toast('Demonstração indisponível. Consulte a execução passo a passo.');});$('#'+kind+'Speed').onchange=e=>v.playbackRate=Number(e.target.value);}
$$('.bottom-nav button').forEach(b=>b.onclick=()=>showScreen(b.dataset.nav));$('#settingsBtn').onclick=showSettings;$('#settingsClose').onclick=()=>$('#settingsDialog').close();$('#saveSettings').onclick=()=>{const date=$('#startDate').value;if(!MotionStore.dateOK(date)||date>MotionStore.localDay()){toast('Informe uma data de início válida, até hoje.');return;}state.settings={startDate:date,morningTime:$('#morningTime').value||'08:00',coreTime:$('#coreTime').value||'19:00',voice:$('#voiceEnabled').checked,dark:$('#darkMode').checked};save();applyTheme();$('#settingsDialog').close();renderHome();toast('Ajustes salvos.');};$('#backupBtn').onclick=backup;$('#importInput').onchange=e=>e.target.files[0]&&importBackup(e.target.files[0]);
$('#homeStartSession').onclick=()=>state.sessionDraft?showScreen('session'):startSession(PRESETS.morning,'morning');$('#homeMapBtn').onclick=()=>showScreen('map');$('#exerciseSearchBtn').onclick=()=>{const hidden=$('#exerciseSearch').classList.toggle('hidden');if(!hidden)$('#exerciseSearch').focus();};$('#exerciseSearch').oninput=renderExercises;
$('#detailBack').onclick=()=>showScreen('exercises');$('#detailStart').onclick=()=>startSession([currentDetail]);$('#favoriteBtn').onclick=()=>{state.favorites=state.favorites.includes(currentDetail)?state.favorites.filter(x=>x!==currentDetail):[...state.favorites,currentDetail];save();updateFavorite();};$$('[data-detail-tab]').forEach(b=>b.onclick=()=>renderDetailTab(b.dataset.detailTab));$('#sessionBack').onclick=()=>showScreen('home');$('#repMinus').onclick=()=>changeTarget(-1);$('#repPlus').onclick=()=>changeTarget(1);$('#timerPlay').onclick=toggleTimer;$('#sessionNext').onclick=completeSessionExercise;
$$('input[name=painRegion]').forEach(r=>r.onchange=()=>{state.painRegion=Number(r.value);save();renderMap();});$$('[data-region]').forEach(b=>b.onclick=()=>{state.painRegion=Number(b.dataset.region);save();renderMap();});$$('[data-map-view]').forEach(b=>b.onclick=()=>{mapView=b.dataset.mapView;renderMap();});$('#clearPain').onclick=()=>{state.painRegion=null;save();renderMap();};$('#mapInfo').onclick=()=>info('Como registrar os sintomas','Selecione a região mais distante em que sente dor ou formigamento. O mapa ilustra um trajeto aproximado e não estabelece diagnóstico. Recuar da perna em direção à lombar é registrado como centralização somente quando há uma região anterior para comparar. Use os exercícios conforme orientação profissional. Pare se houver piora dos sintomas.');$('#exportBtn').onclick=exportCSV;
$('#painAfter').oninput=e=>$('#painValue').textContent=e.target.value+' / 10';$('#finishClose').onclick=()=>$('#finishDialog').close();$('#finishSave').onclick=finishSession;$('#infoClose').onclick=()=>$('#infoDialog').close();
window.onpopstate=e=>showScreen(e.state?.screen||'home',false);window.appPause=pauseMedia;window.appBack=()=>{const open=$('dialog[open]');if(open){open.close();return true;}if(currentScreen!=='home'){showScreen(currentScreen==='detail'?'exercises':'home');return true;}return false;};window.nativeExportDone=ok=>toast(ok?'Arquivo salvo.':'Exportação cancelada.');document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseMedia();});window.addEventListener('pagehide',pauseMedia);let resizeHandle;window.addEventListener('resize',()=>{clearTimeout(resizeHandle);resizeHandle=setTimeout(()=>{if(currentScreen==='progress')renderProgress();},120);});
function icon(name){const paths={info:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20M12 11v6M12 7v.2',export:'M12 3v12M7 10l5 5 5-5M4 17v4h16v-4',home:'M3 10 12 3l9 7v10h-6v-7H9v7H3Z',exercises:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',session:'M9 2h6M12 2v3M18 6l2-2M12 9v5l3 2M12 5a8 8 0 1 0 0 16 8 8 0 0 0 0-16',map:'M12 22s8-8 8-13a8 8 0 0 0-16 0c0 5 8 13 8 13zM12 6a3 3 0 1 0 0 6 3 3 0 0 0 0-6',progress:'M4 20V13M10 20V7M16 20V3M22 20H2',sun:'M12 7a5 5 0 1 0 0 10 5 5 0 0 0 0-10M12 1v3M12 20v3M1 12h3M20 12h3M4 4l2 2M18 18l2 2M20 4l-2 2M6 18l-2 2',chair:'M6 3v10h12V3M4 13h16v4H4zM6 17v5M18 17v5',core:'M3 8v8M7 5v14M7 12h10M17 5v14M21 8v8',walk:'M13 3a2 2 0 1 0 0 4 2 2 0 0 0 0-4M12 8l-3 5-4 1M12 8l4 4 4 1M11 13l3 4 1 5M11 13l-3 8'};return `<svg class="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.walk}"/></svg>`;}
$$('.bottom-nav button').forEach(b=>b.querySelector('span').innerHTML=icon(b.dataset.nav));$('.brand-icon').innerHTML=icon('walk');applyTheme();renderFilters();renderHome();renderExercises();renderMap();history.replaceState({screen:'home'},'','#home');$('#app').dataset.screen='home';

$('#homeMapBtn').innerHTML=icon('map')+'<span>Ver mapa da dor</span>';
function positionMapMarkers(){const img=$('.map-human'),wrap=$('.map-human-wrap');if(!img.naturalWidth)return;const w=wrap.clientWidth,h=wrap.clientHeight,scale=Math.min(w/img.naturalWidth,h/img.naturalHeight),rw=img.naturalWidth*scale,rh=img.naturalHeight*scale,left=(w-rw)/2,top=(h-rh)/2;const xy=mapView==='back'?[[.60,.42],[.73,.53],[.73,.69],[.73,.81],[.71,.94]]:mapView==='front'?[[.51,.46],[.59,.54],[.60,.65],[.61,.79],[.61,.94]]:[[.40,.46],[.46,.54],[.48,.65],[.47,.79],[.48,.93]];$$('[data-region]').forEach((b,i)=>{b.style.left=(left+xy[i][0]*rw)+'px';b.style.top=(top+xy[i][1]*rh)+'px';});}
$('.map-human').addEventListener('load',positionMapMarkers);window.addEventListener('resize',positionMapMarkers);
if('serviceWorker'in navigator&&['https:','http:'].includes(location.protocol))navigator.serviceWorker.register('./service-worker.js').catch(()=>{});

$('#mapInfo').innerHTML=icon('info');$('#exportBtn').innerHTML=icon('export');
