const E=[
{id:'prone',name:'De bruços relaxado',sub:'Alongamento inicial',cat:'Centralização',poster:'prone.jpg',video:'prone.mp4',reps:'—',sets:'—',time:'2 min',steps:['Deite de barriga para baixo em uma superfície firme.','Relaxe lombar e glúteos.','Respire normalmente.','Observe se os sintomas recuam da perna em direção à lombar.']},
{id:'elbows',name:'Apoio nos cotovelos',sub:'Extensão lombar leve',cat:'Centralização',poster:'elbows.jpg',video:'elbows.mp4',reps:'10',sets:'2–3',time:'—',steps:['Deite de barriga para baixo.','Apoie-se nos antebraços.','Mantenha a pelve apoiada.','Suba apenas até uma amplitude confortável.','Retorne devagar.']},
{id:'pressup',name:'Press-up lombar',sub:'McKenzie',cat:'Centralização',poster:'pressup.jpg',video:'pressup.mp4',reps:'10',sets:'2–3',time:'—',steps:['Deite de bruços em uma superfície firme.','Apoie as mãos ao lado do peito.','Estenda os braços, elevando o tronco.','Mantenha o quadril no chão.','Olhe levemente para frente.','Retorne devagar.']},
{id:'chair',name:'Movimentos na cadeira',sub:'Sequência completa',cat:'Cadeira',poster:'chair.jpg',video:'chair-posture.mp4',reps:'10',sets:'2',time:'5–7 min',steps:['Sente-se com os pés apoiados.','Ajuste o tronco e a pelve suavemente.','Use movimentos controlados.','Pare se a dor descer mais para a perna.']},
{id:'neural',name:'Deslizamento neural S1',sub:'Mobilização do nervo ciático',cat:'Neural',poster:'neural.jpg',video:'neural.mp4',reps:'10',sets:'2',time:'—',steps:['Sente-se ereto.','Estenda o joelho esquerdo devagar.','Volte antes de produzir um alongamento forte.','O objetivo é deslizar o nervo, não forçar.']},
{id:'brace',name:'Brace abdominal',sub:'Ativação do core',cat:'Core',poster:'brace.jpg',video:'brace.mp4',reps:'10',sets:'—',time:'8–10 s',steps:['Deite com os joelhos dobrados.','Contraia suavemente o abdômen.','Mantenha a respiração normal.','Segure e relaxe.']},
{id:'bridge',name:'Ponte de glúteos',sub:'Fortalecimento',cat:'Core',poster:'bridge.jpg',video:'bridge.mp4',reps:'8–12',sets:'2–3',time:'—',steps:['Deite com os joelhos dobrados.','Ative abdômen e glúteos.','Eleve o quadril com controle.','Não hiperestenda a lombar.','Retorne devagar.']},
{id:'deadbug',name:'Dead bug',sub:'Estabilização do core',cat:'Core',poster:'deadbug.jpg',video:'deadbug-full.mp4',reps:'6–10',sets:'2–3',time:'—',steps:['Mantenha o abdômen ativo.','Mova braço e perna opostos.','Evite arquear a lombar.','Retorne e alterne os lados.']},
{id:'birddog',name:'Bird-dog',sub:'Estabilidade lombar',cat:'Core',poster:'birddog.jpg',video:'birddog-full.mp4',reps:'6–10',sets:'2–3',time:'—',steps:['Fique em quatro apoios.','Estenda braço e perna opostos.','Mantenha o tronco estável.','Retorne devagar.']},
{id:'side',name:'Prancha lateral',sub:'Core e estabilidade',cat:'Core',poster:'side.jpg',video:'side-full.mp4',reps:'—',sets:'3',time:'10–30 s',steps:['Apoie o antebraço.','Eleve o quadril.','Mantenha o corpo alinhado.','Respire normalmente.']},
{id:'pallof',name:'Pallof press',sub:'Antirrotação',cat:'Core',poster:'pallof.jpg',video:'pallof.mp4',reps:'10–12',sets:'3',time:'—',steps:['Prenda o elástico lateralmente.','Segure junto ao peito.','Empurre as mãos à frente.','Resista à rotação do tronco.']},
{id:'walk',name:'Caminhada',sub:'Atividade aeróbica',cat:'Atividade',poster:'walk.jpg',video:'walk.mp4',reps:'—',sets:'—',time:'10–30 min',steps:['Caminhe em terreno plano.','Use um ritmo confortável.','Aumente o tempo gradualmente.','Interrompa se houver piora distal clara.']}
];

const EXTRA={
prone:{hold:120,muscles:'Posição de repouso em decúbito ventral. A demonstração mostra a postura, sem repetições.',tips:'Use somente se confortável. Não force a extensão nem permaneça se os sintomas avançarem pela perna.',variants:[]},
elbows:{muscles:'Apoio nos antebraços com extensão suave do tronco.',tips:'A pelve fica apoiada. Use apenas a amplitude tolerada.',variants:['prone','pressup']},
pressup:{muscles:'Braços conduzem a elevação do tronco; a pelve permanece no tapete.',tips:'Não faça uma flexão de braços com todo o corpo. Evite forçar o limite do movimento.',variants:['elbows','prone']},
chair:{muscles:'Controle da postura sentada e movimentos leves de pelve e pernas.',tips:'Apoie os pés. Faça pequenas pausas ao longo do dia.',variants:['chair-pelvic','chair-extension','chair-march','sitstand']},
neural:{muscles:'Movimento suave do joelho, com mobilização do trajeto neural.',tips:'Use amplitude pequena e confortável. Não procure alongamento forte ou aumento do formigamento.',variants:['chair-extension']},
brace:{hold:10,muscles:'Ativação suave da parede abdominal, com respiração normal.',tips:'Não prenda a respiração. O corpo permanece apoiado; a ativação não exige grandes movimentos.',variants:['deadbug-simple']},
bridge:{muscles:'Glúteos, musculatura posterior da coxa e estabilizadores do tronco.',tips:'Suba até alinhar tronco e coxas. Não arqueie excessivamente a lombar.',variants:['bridge-march']},
deadbug:{muscles:'Parede abdominal e controle do tronco durante o movimento dos membros.',tips:'Mova braço e perna opostos. Reduza a amplitude se a lombar perder estabilidade.',variants:['deadbug-simple']},
birddog:{muscles:'Estabilizadores do tronco, glúteos e cintura escapular.',tips:'Mantenha a pelve nivelada e evite girar o corpo.',variants:['birddog-simple']},
side:{hold:20,muscles:'Musculatura lateral do tronco e estabilizadores do quadril e ombro.',tips:'Mantenha o apoio confortável e respire. A posição é sustentada, sem balanço.',variants:['side-knees','front-plank']},
pallof:{muscles:'Estabilizadores do tronco em resistência à rotação.',tips:'Use elástico leve e fixação segura na lateral. O tronco não acompanha as mãos.',variants:[]},
walk:{hold:600,muscles:'Atividade global com passos alternados e balanço natural dos braços.',tips:'Escolha terreno plano e ritmo confortável. O tempo pode ser ajustado na sessão.',variants:[]}
};
E.forEach(x=>Object.assign(x,EXTRA[x.id],{poster:x.video.replace('.mp4','.jpg')}));
const VARIANTS=[
{id:'chair-pelvic',name:'Mobilidade pélvica na cadeira',sub:'Movimento suave da pelve',cat:'Cadeira',reps:'10',sets:'2',time:'—',steps:['Sente-se com os pés apoiados.','Faça uma pequena inclinação da pelve.','Retorne à posição neutra sem forçar.']},
{id:'chair-extension',name:'Extensão do joelho na cadeira',sub:'Movimento controlado da perna',cat:'Cadeira',reps:'10',sets:'2',time:'—',steps:['Sente-se ereto e apoie a coxa.','Estenda o joelho dentro de uma amplitude confortável.','Retorne com controle e alterne.']},
{id:'chair-march',name:'Marcha sentada',sub:'Elevação alternada dos joelhos',cat:'Cadeira',reps:'10',sets:'2',time:'—',steps:['Sente-se com os dois pés apoiados.','Eleve um joelho sem inclinar o tronco.','Abaixe e alterne os lados.']},
{id:'sitstand',name:'Sentar e levantar',sub:'Controle e força funcional',cat:'Cadeira',reps:'8–12',sets:'2',time:'—',steps:['Use uma cadeira firme e sem rodas.','Apoie os pés e incline o tronco ligeiramente.','Levante com controle.','Sente novamente devagar.']},
{id:'bridge-march',name:'Ponte com marcha',sub:'Variação avançada de estabilidade',cat:'Core',reps:'6–10',sets:'2',time:'—',steps:['Eleve o quadril na ponte.','Retire um pé ligeiramente do chão.','Mantenha a pelve nivelada.','Apoie o pé e alterne.']},
{id:'deadbug-simple',name:'Dead bug simplificado',sub:'Movimento somente das pernas',cat:'Core',reps:'6–10',sets:'2',time:'—',steps:['Deite com quadris e joelhos flexionados.','Mantenha os braços apontados para cima.','Estenda uma perna sem arquear a lombar.','Retorne e alterne.']},
{id:'birddog-simple',name:'Bird-dog simplificado',sub:'Extensão somente da perna',cat:'Core',reps:'6–10',sets:'2',time:'—',steps:['Fique em quatro apoios.','Estenda uma perna mantendo as mãos apoiadas.','Retorne sem girar a pelve.','Alterne os lados.']},
{id:'side-knees',name:'Prancha lateral com joelhos',sub:'Variação de menor alavanca',cat:'Core',reps:'—',sets:'3',time:'10–20 s',hold:15,steps:['Apoie o antebraço e dobre os joelhos.','Eleve o quadril mantendo os joelhos apoiados.','Respire normalmente durante a sustentação.']},
{id:'front-plank',name:'Prancha frontal',sub:'Sustentação nos antebraços',cat:'Core',reps:'—',sets:'3',time:'10–30 s',hold:20,steps:['Apoie antebraços e pontas dos pés.','Mantenha tronco e pelve alinhados.','Respire normalmente e evite afundar a lombar.']}
];
VARIANTS.forEach(x=>E.push({...x,video:x.id+'.mp4',poster:x.id+'.jpg',muscles:'Controle do tronco e dos apoios na variação demonstrada.',tips:'Escolha a variação adequada à sua orientação e tolerância. A versão avançada exige controle prévio.',variants:[]}));
const PRESETS={morning:['prone','elbows','pressup','walk'],day:['chair','neural','walk'],core:['brace','bridge','deadbug','birddog','side','pallof'],walk:['walk']};
