/* Daily companion: deterministic eligibility and local validation, independent of Gemini. */
(function(root){
'use strict';
const base=typeof module==='object'?require('./planner-core.js'):root.MotionStore;
const obj=x=>x&&typeof x==='object'&&!Array.isArray(x)?x:{};
const text=(x,n=800)=>typeof x==='string'?x.slice(0,n):'';
const integer=(x,a,b)=>Number.isInteger(x)&&x>=a&&x<=b;
const validTime=x=>typeof x==='string'&&Number.isFinite(Date.parse(x));
const choice=(x,a,f=null)=>a.includes(x)?x:f;
const GOALS=['sets','reps','seconds','rest'];
function dose(x){return x&&integer(x.sets,1,3)&&integer(x.reps,1,20)&&integer(x.seconds,1,600)&&integer(x.rest,15,180)?Object.fromEntries(GOALS.map(k=>[k,x[k]])):null;}
const refs=[
{id:'nhs-disc',title:'NHS — Slipped disc',url:'https://www.nhs.uk/conditions/slipped-disc/',principle:'Atividade leve conforme tolerância; reconhecer sinais de alerta. Não confirma que um exercício específico seja indicado para você.'},
{id:'nice-ng59',title:'NICE NG59 — Lombalgia e ciática',url:'https://www.nice.org.uk/guidance/ng59/chapter/recommendations',principle:'Escolher atividades considerando necessidades, preferências e capacidades individuais.'}
];
const questionBank={
 preference:{label:'O que você prefere priorizar hoje, entre as opções já orientadas?',options:[['any','Sem preferência'],['walk','Caminhada'],['floor','Exercícios no colchonete'],['chair','Exercícios na cadeira']]},
 goal:{label:'Qual é seu objetivo principal para esta atividade?',options:[['comfort','Movimentar com conforto'],['consistency','Manter a rotina'],['short','Fazer uma atividade curta']]},
 pacing:{label:'Como você gostaria de organizar a atividade?',options:[['light','Menor volume hoje'],['usual','Até o volume já orientado']]}
};
function defaults(){return{profile:{condition:'Protrusão L5–S1 informada pelo usuário',restrictions:'',approved:{},reviewedAt:null},checkins:[],plans:[],outcomes:[]};}
function answers(x){if(!x||!integer(x.pain,0,10)||!integer(x.region,-1,4)||!integer(x.minutes,3,45)||!['morning','night'].includes(x.period))return null;
 const enums={emergency:['no','yes','unsure'],neurology:['no','yes','unsure'],systemic:['no','yes','unsure'],change:['stable','better','worse','spreading'],followup:['first','better','same','worse','unknown'],energy:['normal','low'],sleep:['good','poor'],floor:['yes','no'],elastic:['yes','no'],restriction:['no','yes','unsure']};
 for(const[k,a]of Object.entries(enums))if(!a.includes(x[k]))return null;
 return{pain:x.pain,region:x.region,minutes:x.minutes,period:x.period,...Object.fromEntries(Object.keys(enums).map(k=>[k,x[k]])),note:text(x.note),excluded:Array.isArray(x.excluded)?x.excluded.filter(y=>typeof y==='string').slice(0,30):[]};
}
function followups(x){return Object.fromEntries(Object.entries(obj(x)).filter(([k,v])=>Object.hasOwn(questionBank,k)&&questionBank[k].options.some(o=>o[0]===v)));}
function normalizeCoach(raw,ids){const r=obj(raw),c=defaults(),p=obj(r.profile);c.profile.condition=text(p.condition,300)||c.profile.condition;c.profile.restrictions=text(p.restrictions);c.profile.reviewedAt=validTime(p.reviewedAt)?p.reviewedAt:null;
 for(const[id,g]of Object.entries(obj(p.approved)))if(ids.includes(id)&&dose(g))c.profile.approved[id]=dose(g);
 const seen=new Set();for(const a of Array.isArray(r.checkins)?r.checkins:[]){const clean=answers(a?.answers);if(!a||!clean||!validTime(a.createdAt)||!base.dateOK(a.day)||typeof a.id!=='string'||seen.has(a.id))continue;seen.add(a.id);c.checkins.push({id:text(a.id,100),day:a.day,createdAt:a.createdAt,answers:clean,followups:followups(a.followups),shared:a.shared===true,gate:choice(a.gate,['ok','emergency','review'],'review')});}
 const planIDs=new Set();for(const p of Array.isArray(r.plans)?r.plans:[]){if(!p||typeof p.id!=='string'||planIDs.has(p.id)||!c.checkins.some(a=>a.id===p.checkinId)||!validTime(p.createdAt)||!base.dateOK(p.day)||!Array.isArray(p.items)||p.items.length>6)continue;
 const items=p.items.filter(x=>ids.includes(x?.exerciseId)&&dose(x.goal)&&['usual','light'].includes(x.variant)).map(x=>({exerciseId:x.exerciseId,goal:dose(x.goal),variant:x.variant,reason:choice(x.reason,['tolerated','time','preference','lighter'],'lighter')}));if(items.length!==p.items.length||new Set(items.map(x=>x.exerciseId)).size!==items.length)continue;planIDs.add(p.id);c.plans.push({id:text(p.id,100),checkinId:text(p.checkinId,100),day:p.day,createdAt:p.createdAt,model:text(p.model,100),period:choice(p.period,['morning','night'],'morning'),items,status:choice(p.status,['suggested','applied','completed','stopped','superseded'],'suggested'),decision:choice(p.decision,['activity','pause'],'pause'),reason:choice(p.reason,['tolerated','time','preference','lighter','review'],'review'),sessionIds:Array.isArray(p.sessionIds)?p.sessionIds.filter(x=>typeof x==='string').map(x=>text(x,100)):[]});}
 for(const o of Array.isArray(r.outcomes)?r.outcomes:[]){if(!o||!c.plans.some(p=>p.id===o.planId)||!validTime(o.createdAt)||!base.dateOK(o.day)||!['better','same','worse','unknown'].includes(o.feeling))continue;c.outcomes.push({id:text(o.id,100),planId:text(o.planId,100),sessionId:text(o.sessionId,100),createdAt:o.createdAt,day:o.day,pain:integer(o.pain,0,10)?o.pain:null,region:integer(o.region,-1,4)?o.region:null,feeling:o.feeling,effort:integer(o.effort,0,10)?o.effort:null,note:text(o.note),stopped:o.stopped===true});}
 return c;
}
function normalize(raw,ids){const s=base.normalize(raw,ids);s.coach=normalizeCoach(raw.coach,ids);s.schemaVersion=9;if(s.sessionDraft){s.sessionDraft.coachPlanId=s.coach.plans.some(p=>p.id===raw.sessionDraft?.coachPlanId)?raw.sessionDraft.coachPlanId:null;}return s;}
function triage(a){if(!answers(a))return{level:'review',message:'Responda todas as perguntas de segurança para continuar.'};
 if(a.emergency!=='no'||a.neurology!=='no')return{level:'emergency',message:'Não inicie a atividade. Alterações novas no controle de urina/fezes, dormência na região íntima, perda de sensibilidade, fraqueza nova ou progressiva, ou trauma importante precisam de atendimento urgente. Procure um pronto atendimento agora; no Brasil, SAMU 192 se necessário. Se ficou em dúvida sobre esses sinais, procure avaliação antes de treinar.'};
 if(a.systemic!=='no'||a.restriction!=='no'||a.pain>=7||['worse','spreading'].includes(a.change)||a.followup==='worse')return{level:'review',message:'A sugestão automática foi pausada. Dor forte, piora, sintomas avançando pela perna, sinais gerais ou restrições precisam ser revistos pelo profissional que acompanha você antes de uma nova atividade.'};return{level:'ok',message:'Nenhum bloqueio identificado nas respostas. Isso não é liberação médica.'};}
function history(s,day){const since=new Date(day+'T12:00:00');since.setDate(since.getDate()-30);const first=base.localDay(since);return{records:s.records.filter(r=>r.localDate>=first&&r.localDate<=day).slice(-160),sessions:s.sessions.filter(r=>r.localDate>=first&&r.localDate<=day).slice(-40),checkins:s.coach.checkins.filter(r=>r.day>=first&&r.day<=day).slice(-30),outcomes:s.coach.outcomes.filter(r=>r.day>=first&&r.day<=day).slice(-40),dailyNotes:Object.fromEntries(Object.entries(s.dailyNotes).filter(([d])=>d>=first&&d<=day)),wellbeing:Object.fromEntries(Object.entries(s.enhanced.wellbeing).filter(([d])=>d>=first&&d<=day))};}
function outcomeConcern(s,o){const p=s.coach.plans.find(p=>p.id===o.planId),before=s.coach.checkins.find(c=>c.id===p?.checkinId)?.answers;return o.feeling==='worse'||o.pain>=7||(before&&o.pain!==null&&o.pain>=before.pain+2)||(before&&o.region!==null&&o.region>=1&&o.region>before.region);}
function estimate(x,hold){return x.sets*(hold?x.seconds:x.reps*6)+Math.max(0,x.sets-1)*x.rest+30;}
function options(s,a,catalog,day,follow={}){if(triage(a).level!=='ok')return[];const reviewed=Date.parse(s.coach.profile.reviewedAt||'1970-01-01'),out=s.coach.outcomes.filter(x=>Date.parse(x.createdAt)>reviewed);if(out.some(x=>outcomeConcern(s,x)))return[];
 const reduced=a.energy==='low'||a.sleep==='poor'||a.followup==='unknown'||follow.pacing==='light';return catalog.flatMap(x=>{const g=dose(s.coach.profile.approved[x.id]);if(!g||x.review||a.excluded.includes(x.id)||s.records.some(r=>r.localDate===day&&r.exerciseId===x.id)||s.records.some(r=>r.exerciseId===x.id&&r.feedback==='worse'&&Date.parse(r.date)>reviewed)||s.enhanced.setLogs.some(r=>r.localDate===day&&r.exerciseId===x.id))return[];
 if(x.id==='pallof'&&a.elastic!=='yes')return[];if(a.floor==='no'&&!['walk','chair','chair-pelvic','chair-extension','chair-march','sitstand'].includes(x.id))return[];
 const light={...g,sets:1,reps:Math.max(1,Math.floor(g.reps/2)),seconds:Math.max(1,Math.floor(g.seconds/2))};return(reduced?[['light',light]]:[['light',light],['usual',g]]).map(([variant,goal])=>({optionId:x.id+':'+variant,exerciseId:x.id,name:x.name,variant,goal,estimatedSeconds:estimate(goal,x.hold)})).filter(o=>o.estimatedSeconds<=a.minutes*60);});}
function validatePlan(raw,allowed,minutes){if(!raw||!['activity','pause'].includes(raw.decision)||!Array.isArray(raw.items)||raw.items.length>6||!['tolerated','time','preference','lighter','review'].includes(raw.reason))throw Error('A IA retornou uma sugestão inválida. Nada foi aplicado.');if(raw.decision==='pause'){if(raw.items.length)throw Error('Resposta inconsistente. Tente novamente.');return{decision:'pause',reason:raw.reason,items:[]};}if(!raw.items.length)throw Error('A IA não selecionou exercícios. Tente novamente.');const seen=new Set();let total=0;const items=raw.items.map(i=>{const o=allowed.find(o=>o.optionId===i?.optionId);if(!o||seen.has(o.exerciseId)||!['tolerated','time','preference','lighter'].includes(i.reason))throw Error('A sugestão contém exercício ou quantidade não autorizados. Nada foi aplicado.');seen.add(o.exerciseId);total+=o.estimatedSeconds;return{exerciseId:o.exerciseId,variant:o.variant,goal:{...o.goal},reason:i.reason};});if(total>minutes*60)throw Error('A sugestão excedeu o tempo disponível. Tente novamente.');return{decision:'activity',reason:raw.reason,items};}
function validateQuestions(raw){if(!raw||!Array.isArray(raw.questions)||raw.questions.length>3||raw.questions.some(x=>!Object.hasOwn(questionBank,x))||new Set(raw.questions).size!==raw.questions.length)throw Error('A IA não retornou perguntas válidas. Tente novamente.');return raw.questions;}
function eligibility(s,p,catalog,now=new Date()){const check=s.coach.checkins.find(x=>x.id===p?.checkinId);if(!check||p.day!==base.localDay(now)||now-Date.parse(check.createdAt)>4*3600000||now<Date.parse(check.createdAt))return'Atualize as respostas: a entrevista vale por até 4 horas e somente no mesmo dia.';if(triage(check.answers).level!=='ok')return triage(check.answers).message;
 const last=s.coach.checkins.at(-1);if(last&&Date.parse(last.createdAt)>Date.parse(check.createdAt))return'Existe uma entrevista mais recente. Gere uma nova sugestão com as respostas atuais.';
 if(!['suggested','applied'].includes(p.status)||p.decision!=='activity')return'Esta sugestão não está disponível para iniciar.';
 const allowed=options(s,check.answers,catalog,p.day,check.followups);const pending=p.items.filter(i=>!s.records.some(r=>p.sessionIds.includes(r.sessionId)&&r.exerciseId===i.exerciseId));for(const i of pending){const match=allowed.find(o=>o.exerciseId===i.exerciseId&&o.variant===i.variant);const inSession=s.sessionDraft?.coachPlanId===p.id&&s.sessionDraft.ids[s.sessionDraft.index]===i.exerciseId;
 if(!match&&!inSession)return'Os registros ou as orientações mudaram. Refaça a entrevista antes de continuar.';
 const approved=dose(s.coach.profile.approved[i.exerciseId]);if(!approved||GOALS.some(k=>k!=='rest'&&i.goal[k]>approved[k]))return'As metas orientadas mudaram. Gere uma nova sugestão.';
 }return null;}
const api={defaults,normalizeCoach,answers,followups,triage,history,options,validatePlan,validateQuestions,eligibility,outcomeConcern,refs,questionBank,dose,estimate};
if(typeof module==='object')module.exports={...api,store:{...base,normalize,defaults:()=>normalize(base.defaults(),[])}};else{root.MotionCoach=api;root.MotionStore={...base,normalize,defaults:()=>normalize(base.defaults(),[])};}
})(typeof window!=='undefined'?window:globalThis);
