/* Pure planning model. Backups retain V4–V7 data, but never contain API secrets. */
(function(root){
'use strict';
const base=typeof module==='object'?require('./state-core.js'):root.MotionStore;
const uniq=a=>[...new Set(a)],periods=['morning','night'],obj=x=>x&&typeof x==='object'&&!Array.isArray(x)?x:{};
const int=(x,lo,hi,f)=>Number.isInteger(x)&&x>=lo&&x<=hi?x:f;
function extras(){return {planSince:base.localDay(),weekly:null,daySlots:{},dayKinds:{},taskStatus:{},goals:{},setLogs:[],wellbeing:{},ai:{model:'gemini-3.5-flash-lite'},reminders:false,autoBackup:false};}
function normalize(raw,ids){const s=base.normalize(raw,ids),e=obj(raw.enhanced),v=extras(),list=a=>uniq((Array.isArray(a)?a:[]).filter(id=>ids.includes(id)));
 v.planSince=base.dateOK(e.planSince)?e.planSince:base.localDay();
 if(Array.isArray(e.weekly)&&e.weekly.length===7)v.weekly=e.weekly.map(d=>({kind:['normal','shift','rest'].includes(d?.kind)?d.kind:'normal',morning:list(d?.morning),night:list(d?.night)}));
 for(const [day,slots] of Object.entries(obj(e.daySlots)))if(base.dateOK(day)&&Array.isArray(slots))v.daySlots[day]=slots.filter(x=>ids.includes(x?.exerciseId)&&periods.includes(x.period)&&typeof x.key==='string'&&x.key.length<180).filter((x,i,a)=>a.findIndex(y=>y.key===x.key)===i).map(x=>({exerciseId:x.exerciseId,period:x.period,key:x.key}));
 for(const [day,kind] of Object.entries(obj(e.dayKinds)))if(base.dateOK(day)&&['normal','shift','rest'].includes(kind))v.dayKinds[day]=kind;
 for(const [day,values] of Object.entries(obj(e.taskStatus)))if(base.dateOK(day)){v.taskStatus[day]={};for(const [k,x]of Object.entries(obj(values)))if(k.length<180&&['skipped','moved'].includes(x?.status))v.taskStatus[day][k]={status:x.status,to:base.dateOK(x.to)?x.to:null};}
 for(const [id,g]of Object.entries(obj(e.goals)))if(ids.includes(id))v.goals[id]={sets:int(g.sets,1,20,1),reps:int(g.reps,1,999,10),seconds:int(g.seconds,1,3600,30),rest:int(g.rest,0,600,30)};
 const seen=new Set();v.setLogs=(Array.isArray(e.setLogs)?e.setLogs:[]).filter(x=>x&&ids.includes(x.exerciseId)&&base.dateOK(x.localDate)&&typeof x.id==='string'&&!seen.has(x.id)&&seen.add(x.id)).map(x=>({id:x.id.slice(0,180),exerciseId:x.exerciseId,localDate:x.localDate,sessionId:String(x.sessionId||'').slice(0,100),slotKey:String(x.slotKey||'').slice(0,180),set:int(x.set,1,20,1),reps:int(x.reps,1,999,null),seconds:int(x.seconds,1,3600,null),date:Number.isFinite(Date.parse(x.date))?x.date:new Date(x.localDate+'T12:00:00').toISOString()}));
 for(const[day,w]of Object.entries(obj(e.wellbeing)))if(base.dateOK(day))v.wellbeing[day]={walk:int(w.walk,0,1440,null),sit:int(w.sit,0,1440,null)};
 if(typeof e.ai?.model==='string'&&/^[a-zA-Z0-9._-]{1,100}$/.test(e.ai.model))v.ai.model=e.ai.model;
 v.reminders=e.reminders===true;v.autoBackup=e.autoBackup===true;
 s.records.forEach((r,i)=>{const x=raw.records?.[i]||{};r.slotKey=typeof x.slotKey==='string'?x.slotKey.slice(0,180):null;r.feedback=['better','same','worse'].includes(x.feedback)?x.feedback:null;});
 if(s.sessionDraft){const d=raw.sessionDraft;if(d.ids.every(id=>ids.includes(id))){s.sessionDraft.ids=[...d.ids];s.sessionDraft.index=d.index;}s.sessionDraft.setIndex=int(d.setIndex,0,19,0);s.sessionDraft.restUntil=Number.isFinite(d.restUntil)?Math.max(0,d.restUntil):0;s.sessionDraft.slotKeys=Array.isArray(d.slotKeys)?d.slotKeys.map(x=>typeof x==='string'?x.slice(0,180):null):[];s.sessionDraft.setGoal=d.setGoal?{sets:int(d.setGoal.sets,1,20,1),reps:int(d.setGoal.reps,1,999,10),seconds:int(d.setGoal.seconds,1,3600,30),rest:int(d.setGoal.rest,0,600,30)}:null;}
 s.schemaVersion=8;s.enhanced=v;return s;
}
function defaultState(){return normalize(base.defaults(),[]);}
function weekday(day){return new Date(day+'T12:00:00').getDay();}
function slots(s,day){const e=s.enhanced;if(Object.hasOwn(e.daySlots,day))return e.daySlots[day];if(day<e.planSince)return(s.dailyPlans[day]||[]).map(id=>({exerciseId:id,period:"morning",key:id+"@morning"}));const w=e.weekly?.[weekday(day)];if(w)return w.kind==='rest'?[]:periods.flatMap(period=>w[period].map(id=>({exerciseId:id,period,key:id+'@'+period})));
 return(s.dailyPlans[day]||s.routine).map(id=>({exerciseId:id,period:'morning',key:id+'@morning'}));}
function status(s,day,slot){if(s.records.some(r=>r.localDate===day&&r.exerciseId===slot.exerciseId&&(r.slotKey===slot.key||(!r.slotKey&&slots(s,day).find(x=>x.exerciseId===r.exerciseId)?.key===slot.key))))return 'done';return s.enhanced.taskStatus[day]?.[slot.key]?.status||'pending';}
function kind(s,day){return s.enhanced.dayKinds[day]||(day<s.enhanced.planSince?'normal':s.enhanced.weekly?.[weekday(day)]?.kind)||'normal';}
function snapshot(s,day){if(!Object.hasOwn(s.enhanced.daySlots,day)){s.enhanced.daySlots[day]=slots(s,day).map(x=>({...x}));s.enhanced.dayKinds[day]=kind(s,day);}s.dailyPlans[day]=uniq(s.enhanced.daySlots[day].map(x=>x.exerciseId));}
function move(s,day,key,to,period){if(!base.dateOK(to)||to<=day||!periods.includes(period))throw Error('Escolha um dia posterior.');snapshot(s,day);snapshot(s,to);const slot=slots(s,day).find(x=>x.key===key);if(!slot||status(s,day,slot)!=='pending')throw Error('Atividade não está pendente.');const target={exerciseId:slot.exerciseId,period,key:slot.exerciseId+'@'+period};if(slots(s,to).some(x=>x.key===target.key))throw Error('Esse exercício já está planejado neste período.');s.enhanced.daySlots[to].push(target);s.enhanced.dayKinds[to]='normal';(s.enhanced.taskStatus[day]||={})[key]={status:'moved',to};s.dailyPlans[to]=uniq(slots(s,to).map(x=>x.exerciseId));}
function week(s,start){const days=Array.from({length:7},(_,i)=>{const d=new Date(start+'T12:00:00');d.setDate(d.getDate()+i);return base.localDay(d);});let planned=0,done=0,skipped=0,moved=0;for(const day of days)for(const slot of slots(s,day)){const st=status(s,day,slot);if(st==='moved'){moved++;continue;}planned++;if(st==='done')done++;if(st==='skipped')skipped++;}const records=s.records.filter(r=>days.includes(r.localDate));const pain=days.flatMap(day=>{const n=s.dailyNotes[day];if(n?.pain!=null)return[{day,pain:n.pain}];const a=s.sessions.filter(x=>x.localDate===day);return a.length?[{day,pain:a.at(-1).pain}]:[];});return {days,planned,done,skipped,moved,percent:planned?Math.round(done/planned*100):null,practiceDays:new Set(records.map(r=>r.localDate)).size,executions:records.length,pain,wellbeing:days.map(day=>({day,...s.enhanced.wellbeing[day]})),feedback:{better:records.filter(r=>r.feedback==='better').length,same:records.filter(r=>r.feedback==='same').length,worse:records.filter(r=>r.feedback==='worse').length}};}
const api={...base,normalize,defaults:defaultState,slots,status,kind,snapshot,move,week};if(typeof module==='object')module.exports=api;else root.MotionStore=api;
})(typeof window!=='undefined'?window:globalThis);
