'use strict';
const CACHE='l5s1-studio-v7';
const ASSETS=["./", "./index.html", "./styles.css", "./state-core.js", "./catalog.js", "./app.js", "./manifest.webmanifest", "./icons/icon-192.png", "./icons/icon-512.png", "./posters/birddog-human.jpg", "./posters/deadbug-human.jpg", "./posters/map-front.svg", "./posters/map-left.svg", "./posters/pain_map_realistic.jpg", "./media/01-prone-reference.png", "./media/02-elbows-reference.png", "./media/03-pressup-reference.png", "./media/04-chair-reference.png", "./media/05-neural-reference.png", "./media/06-brace-reference.png", "./media/07-bridge-reference.png", "./media/10-side-plank-reference.png", "./media/11-pallof-reference.png", "./media/12-walk-reference.png", "./media/13-chair-pelvic-reference.png", "./media/14-chair-extension-reference.png", "./media/15-chair-march-reference.png", "./media/16-sitstand-reference.png", "./media/17-bridge-march-reference.png", "./media/18-deadbug-simple-reference.png", "./media/19-birddog-simple-reference.png", "./media/20-side-knees-reference.png", "./media/21-front-plank-reference.png", "./media/birddog-human.mp4", "./media/deadbug-human.mp4"];
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('l5s1-studio-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',e=>{
 if(e.request.method!=='GET'||new URL(e.request.url).origin!==self.location.origin)return;
 e.respondWith((async()=>{const cached=await caches.match(e.request.url);if(!cached)return fetch(e.request);const range=e.request.headers.get('Range');if(!range)return cached;const match=/^bytes=(\d+)-(\d*)$/.exec(range);if(!match)return fetch(e.request);const bytes=await cached.arrayBuffer(),start=Number(match[1]),end=Math.min(match[2]?Number(match[2]):bytes.byteLength-1,bytes.byteLength-1);if(start>end||start>=bytes.byteLength)return new Response(null,{status:416,headers:{'Content-Range':'bytes */'+bytes.byteLength}});return new Response(bytes.slice(start,end+1),{status:206,headers:{'Content-Type':cached.headers.get('Content-Type')||'video/mp4','Content-Length':String(end-start+1),'Content-Range':`bytes ${start}-${end}/${bytes.byteLength}`,'Accept-Ranges':'bytes'}});})());
});
